export const CSV_DATA = `Question 1.,Question 2.,Question 3.,Question 4.,Question 5.,Final Options to Display,Cost / Per,Turnaround,Completion Date,Max Insured Value,Service Descriptions
Pregrading (2000 - Newer Only),X,X,X,2000 - Newer Only,M2M Pregrading (2000 - Newer Only),$7.00,5,3/13/2026,$500.00,"Cards from Year 2000 and Newer Only. This service is not required if you only wish to receive the standard submission wipe- down— all Market 2 Mint submissions automatically include our professional wipe- down service. Our team will carefully evaluate each card’s surface, centering, edges, and corners, then provide you with an interactive report highlighting key defects and projected grades. You can easily mark your submit and non-submit selections directly within the report, and your items will be processed/returned accordingly."
Trading Cards,PSA,No,X,Card Grade Only,PSA Value Bulk (1980 - Newer),$29.99,105,6/21/2026,$500.00,"Value Bulk service is ideal for collectors who want a complete, worry-free grading experience. Designed for modern-era cards with pack-pulled autographs (Only the card can be graded), this service includes a professional wipe-down to help remove surface dust and fingerprints prior to submission. We handle every step with care: providing fresh Card Savers & penny sleeves, capturing high-resolution scans of your cards, and ensuring secure hand-delivery and pickup directly at PSA. An excellent choice for collectors seeking professional preparation, reliable grading, and long-term protection to help maximize their cards’ appearance and value."
Trading Cards,PSA,Yes,Pack-pulled,Card Grade Only,PSA Value Bulk (1980 - Newer),$29.99,105,6/21/2026,$500.00,"Value Bulk service is ideal for collectors who want a complete, worry-free grading experience. Designed for modern-era cards with pack-pulled autographs (Only the card can be graded), this service includes a professional wipe-down to help remove surface dust and fingerprints prior to submission. We handle every step with care: providing fresh Card Savers & penny sleeves, capturing high-resolution scans of your cards, and ensuring secure hand-delivery and pickup directly at PSA. An excellent choice for collectors seeking professional preparation, reliable grading, and long-term protection to help maximize their cards’ appearance and value."
Trading Cards,PSA,No,X,Card Grade Only,PSA Value (1980 - Newer),$37.99,75,5/22/2026,$500.00,"Can have a pack-pulled auto but only card is graded. This service is perfect for grading vintage-era and modern cards at an affordable rate. PSA’s Value tier allows collectors to preserve and authenticate classic cards valued up to $500. All cards submitted through Market 2 Mint receive wipe-down and careful handling throughout the submission process."
Trading Cards,PSA,Yes,Pack-pulled,Card Grade Only,PSA Value (1980 - Newer),$37.99,75,5/22/2026,$500.00,"Can have a pack-pulled auto but only card is graded. This service is perfect for grading vintage-era and modern cards at an affordable rate. PSA’s Value tier allows collectors to preserve and authenticate classic cards valued up to $500. All cards submitted through Market 2 Mint receive wipe-down and careful handling throughout the submission process."
Trading Cards,PSA,No,X,Authenticate Only,PSA Value (Auth Only),$37.99,75,5/22/2026,$500.00,"Can have a pack-pulled auto but only card is graded. This service is perfect for grading vintage-era and modern cards at an affordable rate. PSA’s Value tier allows collectors to preserve and authenticate classic cards valued up to $500. All cards submitted through Market 2 Mint receive wipe-down and careful handling throughout the submission process."
Trading Cards,PSA,Yes,Pack-pulled,Authenticate Only,PSA Value (Auth Only),$47.99,85,6/1/2026,$500.00,"Can have a pack-pulled auto but only card is graded. This service is perfect for grading vintage-era and modern cards at an affordable rate. PSA’s Value tier allows collectors to preserve and authenticate classic cards valued up to $500. All cards submitted through Market 2 Mint receive wipe-down and careful handling throughout the submission process."
Trading Cards,PSA,Yes,Pack-pulled,Card & Autograph Grade,PSA Value (Dual),$47.99,85,6/1/2026,$500.00,"Can have a pack-pulled auto but only card is graded. This service is perfect for grading vintage-era and modern cards at an affordable rate. PSA’s Value tier allows collectors to preserve and authenticate classic cards valued up to $500. All cards submitted through Market 2 Mint receive wipe-down and careful handling throughout the submission process."
Trading Cards,PSA,Yes,Aftermarket,Card & Autograph Grade,PSA Value (Dual),$47.99,85,6/1/2026,$500.00,"Can have a pack-pulled auto but only card is graded. This service is perfect for grading vintage-era and modern cards at an affordable rate. PSA’s Value tier allows collectors to preserve and authenticate classic cards valued up to $500. All cards submitted through Market 2 Mint receive wipe-down and careful handling throughout the submission process."
Trading Cards,PSA,No,X,Card Grade Only,PSA Vintage (1979 - Older),$37.99,75,5/22/2026,$500.00,"Can have a pack-pulled auto but only card is graded. This service is perfect for grading vintage-era and modern cards at an affordable rate. PSA’s Value tier allows collectors to preserve and authenticate classic cards valued up to $500. All cards submitted through Market 2 Mint receive wipe-down and careful handling throughout the submission process."
Trading Cards,PSA,No,X,Authenticate Only,PSA Vintage (1979 - Older) (Auth Only),$37.99,75,5/22/2026,$500.00,"Can have a pack-pulled auto but only card is graded. This service is perfect for grading vintage-era and modern cards at an affordable rate. PSA’s Value tier allows collectors to preserve and authenticate classic cards valued up to $500. All cards submitted through Market 2 Mint receive wipe-down and careful handling throughout the submission process."
Trading Cards,PSA,Yes,Aftermarket,Card & Autograph Grade,PSA Vintage (1979 - Older) (Dual),$47.99,85,6/1/2026,$500.00,"Can have a pack-pulled auto but only card is graded. This service is perfect for grading vintage-era and modern cards at an affordable rate. PSA’s Value tier allows collectors to preserve and authenticate classic cards valued up to $500. All cards submitted through Market 2 Mint receive wipe-down and careful handling throughout the submission process."
Trading Cards,PSA,Yes,Aftermarket,Authenticate Only,PSA Vintage (1979 - Older) (Auth Only),$47.99,85,6/1/2026,$500.00,"Can have a pack-pulled auto but only card is graded. This service is perfect for grading vintage-era and modern cards at an affordable rate. PSA’s Value tier allows collectors to preserve and authenticate classic cards valued up to $500. All cards submitted through Market 2 Mint receive wipe-down and careful handling throughout the submission process."
Trading Cards,PSA,Yes,Pack-pulled,Card Grade Only,PSA Value Plus,$54.99,45,4/22/2026,$500.00,"PSA’s Value Plus service offers a faster turnaround for mid-value cards—perfect for collectors who want efficiency without the higher cost of premium tiers. As always, Market 2 Mint provides wipe-downs and secure handling for every card submitted."
Trading Cards,PSA,No,X,Card Grade Only,PSA Value Plus,$54.99,45,4/22/2026,$500.00,"PSA’s Value Plus service offers a faster turnaround for mid-value cards—perfect for collectors who want efficiency without the higher cost of premium tiers. As always, Market 2 Mint provides wipe-downs and secure handling for every card submitted."
Trading Cards,PSA,Yes,Pack-pulled,Authenticate Only,PSA Value Plus (Auth),$54.99,45,4/22/2026,$500.00,"PSA’s Value Plus service offers a faster turnaround for mid-value cards—perfect for collectors who want efficiency without the higher cost of premium tiers. As always, Market 2 Mint provides wipe-downs and secure handling for every card submitted."
Trading Cards,PSA,No,X,Authenticate Only,PSA Value Plus (Auth),$54.99,45,4/22/2026,$500.00,"PSA’s Value Plus service offers a faster turnaround for mid-value cards—perfect for collectors who want efficiency without the higher cost of premium tiers. As always, Market 2 Mint provides wipe-downs and secure handling for every card submitted."
Trading Cards,PSA,Yes,Aftermarket,Card & Autograph Grade,PSA Value Plus (Dual),$69.99,55,5/2/2026,$500.00,"PSA’s Value Plus service offers a faster turnaround for mid-value cards—perfect for collectors who want efficiency without the higher cost of premium tiers. As always, Market 2 Mint provides wipe-downs and secure handling for every card submitted."
Trading Cards,PSA,Yes,Aftermarket,Autograph Grade Only,PSA Value Plus (Auto),$69.99,55,5/2/2026,$500.00,"PSA’s Value Plus service offers a faster turnaround for mid-value cards—perfect for collectors who want efficiency without the higher cost of premium tiers. As always, Market 2 Mint provides wipe-downs and secure handling for every card submitted."
Trading Cards,PSA,Yes,Aftermarket,Authenticate Only,PSA Value Plus (Auth),$69.99,55,5/2/2026,$500.00,"PSA’s Value Plus service offers a faster turnaround for mid-value cards—perfect for collectors who want efficiency without the higher cost of premium tiers. As always, Market 2 Mint provides wipe-downs and secure handling for every card submitted."
Trading Cards,PSA,Yes,Pack-pulled,Card & Autograph Grade,PSA Value Max (Dual),$89.99,45,4/22/2026,"$1,000.00","PSA’s Value Max Dual option offers a solid balance between cost and turnaround time for pack-pulled and aftermarket autographs. All cards submitted through Market 2 Mint receive a wipe-down and are handled with care from start to finish."
Trading Cards,PSA,Yes,Pack-pulled,Autograph Grade Only,PSA Value Max (Auto),$89.99,45,4/22/2026,"$1,000.00","PSA’s Value Max Dual option offers a solid balance between cost and turnaround time for pack-pulled and aftermarket autographs. All cards submitted through Market 2 Mint receive a wipe-down and are handled with care from start to finish."
Trading Cards,PSA,Yes,Pack-pulled,Authenticate Only,PSA Value Max (Auth),$89.99,45,4/22/2026,"$1,000.00","PSA’s Value Max Dual option offers a solid balance between cost and turnaround time for pack-pulled and aftermarket autographs. All cards submitted through Market 2 Mint receive a wipe-down and are handled with care from start to finish."
Trading Cards,PSA,Yes,Aftermarket,Card & Autograph Grade,PSA Value Max (Dual),$89.99,45,4/22/2026,"$1,000.00","PSA’s Value Max Dual option offers a solid balance between cost and turnaround time for pack-pulled and aftermarket autographs. All cards submitted through Market 2 Mint receive a wipe-down and are handled with care from start to finish."
Trading Cards,PSA,Yes,Aftermarket,Autograph Grade Only,PSA Value Max (Auto),$89.99,45,4/22/2026,"$1,000.00","PSA’s Value Max Dual option offers a solid balance between cost and turnaround time for pack-pulled and aftermarket autographs. All cards submitted through Market 2 Mint receive a wipe-down and are handled with care from start to finish."
Trading Cards,PSA,Yes,Aftermarket,Authenticate Only,PSA Value Max (Auth),$89.99,45,4/22/2026,"$1,000.00","PSA’s Value Max Dual option offers a solid balance between cost and turnaround time for pack-pulled and aftermarket autographs. All cards submitted through Market 2 Mint receive a wipe-down and are handled with care from start to finish."
Trading Cards,PSA,Yes,Pack-pulled,Card Grade Only,PSA Regular,$84.99,25,4/2/2026,"$1,500.00","PSA’s Regular service is ideal for grading mid-to-high value cards with a faster turnaround than other options. Whether you're grading for resale or personal collection, this service delivers trusted results with efficiency. All cards submitted through Market 2 Mint receive a full wipe-down and secure handling throughout the process."
Trading Cards,PSA,No,X,Card Grade Only,PSA Regular,$84.99,25,4/2/2026,"$1,500.00","PSA’s Regular service is ideal for grading mid-to-high value cards with a faster turnaround than other options. Whether you're grading for resale or personal collection, this service delivers trusted results with efficiency. All cards submitted through Market 2 Mint receive a full wipe-down and secure handling throughout the process."
Trading Cards,PSA,Yes,Pack-pulled,Authenticate Only,PSA Regular (Auth),$84.99,25,4/2/2026,"$1,500.00","PSA’s Regular service is ideal for grading mid-to-high value cards with a faster turnaround than other options. Whether you're grading for resale or personal collection, this service delivers trusted results with efficiency. All cards submitted through Market 2 Mint receive a full wipe-down and secure handling throughout the process."
Trading Cards,PSA,No,X,Authenticate Only,PSA Regular (Auth),$84.99,25,4/2/2026,"$1,500.00","PSA’s Regular service is ideal for grading mid-to-high value cards with a faster turnaround than other options. Whether you're grading for resale or personal collection, this service delivers trusted results with efficiency. All cards submitted through Market 2 Mint receive a full wipe-down and secure handling throughout the process."
Trading Cards,PSA,Yes,Pack-pulled,Card & Autograph Grade,PSA Regular (Dual),$109.99,25,4/2/2026,"$1,500.00","PSA’s Regular service is ideal for grading mid-to-high value cards with a faster turnaround than other options. Whether you're grading for resale or personal collection, this service delivers trusted results with efficiency. All cards submitted through Market 2 Mint receive a full wipe-down and secure handling throughout the process."
Trading Cards,PSA,Yes,Pack-pulled,Autograph Grade Only,PSA Regular (Auto),$109.99,25,4/2/2026,"$1,500.00","PSA’s Regular service is ideal for grading mid-to-high value cards with a faster turnaround than other options. Whether you're grading for resale or personal collection, this service delivers trusted results with efficiency. All cards submitted through Market 2 Mint receive a full wipe-down and secure handling throughout the process."
Trading Cards,PSA,Yes,Pack-pulled,Authenticate Only,PSA Regular (Auth),$109.99,25,4/2/2026,"$1,500.00","PSA’s Regular service is ideal for grading mid-to-high value cards with a faster turnaround than other options. Whether you're grading for resale or personal collection, this service delivers trusted results with efficiency. All cards submitted through Market 2 Mint receive a full wipe-down and secure handling throughout the process."
Trading Cards,PSA,Yes,Aftermarket,Card & Autograph Grade,PSA Regular (Dual),$109.99,25,4/2/2026,"$1,500.00","PSA’s Regular service is ideal for grading mid-to-high value cards with a faster turnaround than other options. Whether you're grading for resale or personal collection, this service delivers trusted results with efficiency. All cards submitted through Market 2 Mint receive a full wipe-down and secure handling throughout the process."
Trading Cards,PSA,Yes,Aftermarket,Autograph Grade Only,PSA Regular (Auto),$109.99,25,4/2/2026,"$1,500.00","PSA’s Regular service is ideal for grading mid-to-high value cards with a faster turnaround than other options. Whether you're grading for resale or personal collection, this service delivers trusted results with efficiency. All cards submitted through Market 2 Mint receive a full wipe-down and secure handling throughout the process."
Trading Cards,PSA,Yes,Aftermarket,Authenticate Only,PSA Regular (Auth),$109.99,25,4/2/2026,"$1,500.00","PSA’s Regular service is ideal for grading mid-to-high value cards with a faster turnaround than other options. Whether you're grading for resale or personal collection, this service delivers trusted results with efficiency. All cards submitted through Market 2 Mint receive a full wipe-down and secure handling throughout the process."
Trading Cards,PSA,Yes,Pack-pulled,Card Grade Only,PSA Express,$154.00,25,4/2/2026,"$2,500.00","PSA’s Express service offers priority turnaround and grader notes. Perfect for collectors or sellers who need quick results without sacrificing PSA’s trusted grading standards. All submissions through Market 2 Mint include card prep, wipe-down, and secure handling from start to finish."
Trading Cards,PSA,No,X,Card Grade Only,PSA Express,$154.00,25,4/2/2026,"$2,500.00","PSA’s Express service offers priority turnaround and grader notes. Perfect for collectors or sellers who need quick results without sacrificing PSA’s trusted grading standards. All submissions through Market 2 Mint include card prep, wipe-down, and secure handling from start to finish."
Trading Cards,PSA,Yes,Pack-pulled,Authenticate Only,PSA Express (Auth),$154.00,25,4/2/2026,"$2,500.00","PSA’s Express service offers priority turnaround and grader notes. Perfect for collectors or sellers who need quick results without sacrificing PSA’s trusted grading standards. All submissions through Market 2 Mint include card prep, wipe-down, and secure handling from start to finish."
Trading Cards,PSA,No,X,Authenticate Only,PSA Express (Auth),$154.00,25,4/2/2026,"$2,500.00","PSA’s Express service offers priority turnaround and grader notes. Perfect for collectors or sellers who need quick results without sacrificing PSA’s trusted grading standards. All submissions through Market 2 Mint include card prep, wipe-down, and secure handling from start to finish."
Trading Cards,PSA,Yes,Pack-pulled,Card & Autograph Grade,PSA Express (Dual),$204.00,25,4/2/2026,"$2,500.00","PSA’s Express service offers priority turnaround and grader notes. Perfect for collectors or sellers who need quick results without sacrificing PSA’s trusted grading standards. All submissions through Market 2 Mint include card prep, wipe-down, and secure handling from start to finish."
Trading Cards,PSA,Yes,Pack-pulled,Autograph Grade Only,PSA Express (Auto),$204.00,25,4/2/2026,"$2,500.00","PSA’s Express service offers priority turnaround and grader notes. Perfect for collectors or sellers who need quick results without sacrificing PSA’s trusted grading standards. All submissions through Market 2 Mint include card prep, wipe-down, and secure handling from start to finish."
Trading Cards,PSA,Yes,Pack-pulled,Authenticate Only,PSA Express (Auth),$204.00,25,4/2/2026,"$2,500.00","PSA’s Express service offers priority turnaround and grader notes. Perfect for collectors or sellers who need quick results without sacrificing PSA’s trusted grading standards. All submissions through Market 2 Mint include card prep, wipe-down, and secure handling from start to finish."
Trading Cards,PSA,Yes,Aftermarket,Card & Autograph Grade,PSA Express (Dual),$204.00,25,4/2/2026,"$2,500.00","PSA’s Express service offers priority turnaround and grader notes. Perfect for collectors or sellers who need quick results without sacrificing PSA’s trusted grading standards. All submissions through Market 2 Mint include card prep, wipe-down, and secure handling from start to finish."
Trading Cards,PSA,Yes,Aftermarket,Autograph Grade Only,PSA Express (Auto),$204.00,25,4/2/2026,"$2,500.00","PSA’s Express service offers priority turnaround and grader notes. Perfect for collectors or sellers who need quick results without sacrificing PSA’s trusted grading standards. All submissions through Market 2 Mint include card prep, wipe-down, and secure handling from start to finish."
Trading Cards,PSA,Yes,Aftermarket,Authenticate Only,PSA Express (Auth),$204.00,25,4/2/2026,"$2,500.00","PSA’s Express service offers priority turnaround and grader notes. Perfect for collectors or sellers who need quick results without sacrificing PSA’s trusted grading standards. All submissions through Market 2 Mint include card prep, wipe-down, and secure handling from start to finish."
Trading Cards,PSA,Yes,Pack-pulled,Card Grade Only,PSA Super Express,$304.00,15,3/23/2026,"$5,000.00","Need fast grading for your high- value cards? PSA’s Super Express service is built for speed and security, offering fast turnaround and grader notes. This service ensures your premium items are prioritized and handled with top-tier care. All submissions through Market 2 Mint include a professional wipe-down and secure processing from start to finish."
Trading Cards,PSA,No,X,Card Grade Only,PSA Super Express,$304.00,15,3/23/2026,"$5,000.00","Need fast grading for your high- value cards? PSA’s Super Express service is built for speed and security, offering fast turnaround and grader notes. This service ensures your premium items are prioritized and handled with top-tier care. All submissions through Market 2 Mint include a professional wipe-down and secure processing from start to finish."
Trading Cards,PSA,Yes,Pack-pulled,Authenticate Only,PSA Super Express (Auth),$304.00,20,3/28/2026,"$5,000.00","Need fast grading for your high- value cards? PSA’s Super Express service is built for speed and security, offering fast turnaround and grader notes. This service ensures your premium items are prioritized and handled with top-tier care. All submissions through Market 2 Mint include a professional wipe-down and secure processing from start to finish."
Trading Cards,PSA,No,X,Authenticate Only,PSA Super Express (Auth),$304.00,20,3/28/2026,"$5,000.00","Need fast grading for your high- value cards? PSA’s Super Express service is built for speed and security, offering fast turnaround and grader notes. This service ensures your premium items are prioritized and handled with top-tier care. All submissions through Market 2 Mint include a professional wipe-down and secure processing from start to finish."
Trading Cards,BGS,No,X,X,BGS Base,$25.00,45,4/22/2026,"$1,500.00","Beckett’s Base service offers reliable grading with no maximum declared value, making it ideal for a wide range of cards—from modern to vintage. This service provides full subgrades and the iconic BGS label. All cards submitted through Market 2 Mint receive a full wipe-down and are securely handled from prep to return."
Trading Cards,BGS,Yes,Pack-pulled,X,BGS Base w/Auto,$29.00,55,5/2/2026,"$1,500.00","Beckett’s Base service offers reliable grading with no maximum declared value, making it ideal for a wide range of cards—from modern to vintage. This service provides full subgrades and the iconic BGS label. All cards submitted through Market 2 Mint receive a full wipe-down and are securely handled from prep to return."
Trading Cards,BGS,No,X,X,BGS Standard,$40.00,30,4/7/2026,"$2,500.00","BGS Standard offers a great balance between turnaround time and cost, with no maximum declared value. Perfect for collectors looking for reliable grading with full subgrades and Beckett’s signature labeling. All cards submitted through Market 2 Mint are wiped down and securely handled throughout the submission process."
Trading Cards,BGS,Yes,Pack-pulled,X,BGS Standard w/Auto,$45.00,35,4/12/2026,"$2,500.00","BGS Standard offers a great balance between turnaround time and cost, with no maximum declared value. Perfect for collectors looking for reliable grading with full subgrades and Beckett’s signature labeling. All cards submitted through Market 2 Mint are wiped down and securely handled throughout the submission process."
Trading Cards,BGS,No,X,X,BGS Express,$85.00,15,3/23/2026,"$5,000.00","Need faster grading without sacrificing accuracy? BGS Express offers a quicker turnaround—with no maximum declared value. This service includes full subgrades and Beckett’s premium labeling, ideal for collectors and sellers who want their cards back fast. Every card submitted through Market 2 Mint receives a careful wipe- down and is securely processed from start to finish."
Trading Cards,BGS,Yes,Pack-pulled,X,BGS Express w/Auto,$90.00,20,3/28/2026,"$5,000.00","Need faster grading without sacrificing accuracy? BGS Express offers a quicker turnaround—with no maximum declared value. This service includes full subgrades and Beckett’s premium labeling, ideal for collectors and sellers who want their cards back fast. Every card submitted through Market 2 Mint receives a careful wipe- down and is securely processed from start to finish."
Trading Cards,CGC,No,X,X,CGC Economy,$23.50,35,4/12/2026,"$1,000.00","CGC’s Economy service is an ideal option for collectors looking for reliable grading without the higher price tag. Whether you’re submitting sports cards or trading card games (TCGs), CGC delivers consistent, high-quality results. Every card submitted through Market 2 Mint is wiped down and carefully handled throughout the grading process."
Trading Cards,CGC,Yes,Pack-pulled,X,CGC Economy w/Auto,$27.50,35,4/12/2026,"$1,000.00","CGC’s Economy service is an ideal option for collectors looking for reliable grading without the higher price tag. Whether you’re submitting sports cards or trading card games (TCGs), CGC delivers consistent, high-quality results. Every card submitted through Market 2 Mint is wiped down and carefully handled throughout the grading process."
Trading Cards,CGC,No,X,X,CGC Standard,$60.00,25,4/2/2026,"$3,000.00","CGC’s Standard service is a great choice for grading mid-value cards, offering a perfect blend of turnaround time and affordability. Whether it’s sports cards or TCGs, you’ll receive accurate, professional grading with CGC’s trusted standards. All cards submitted through Market 2 Mint are wiped down and securely handled from submission to return."
Trading Cards,CGC,Yes,Pack-pulled,X,CGC Standard w/Auto,$65.00,25,4/2/2026,"$3,000.00","CGC’s Standard service is a great choice for grading mid-value cards, offering a perfect blend of turnaround time and affordability. Whether it’s sports cards or TCGs, you’ll receive accurate, professional grading with CGC’s trusted standards. All cards submitted through Market 2 Mint are wiped down and securely handled from submission to return."
Trading Cards,CGC,No,X,X,CGC Express,$105.00,15,3/23/2026,"$10,000.00","CGC’s Express service is ideal for grading high-value cards quickly and securely. Perfect for serious collectors or sellers who need fast, reliable results. All cards submitted through Market 2 Mint are wiped down and professionally handled from start to finish."
Trading Cards,CGC,Yes,Pack-pulled,X,CGC Express w/Auto,$110.00,15,3/23/2026,"$10,000.00","CGC’s Express service is ideal for grading high-value cards quickly and securely. Perfect for serious collectors or sellers who need fast, reliable results. All cards submitted through Market 2 Mint are wiped down and professionally handled from start to finish."
Trading Cards,SGC,No,X,X,SGC <1500,$23.50,25,4/2/2026,"$1,500.00","SGC’s <1500 service offers affordable grading for cards valued up to $1,500, making it a great option for collectors looking for reliable grading without the higher price tag. Whether you’re submitting sports cards or trading card games (TCGs), SGC delivers consistent, high-quality results. Every card submitted through Market 2 Mint is wiped down and carefully handled throughout the grading process."
Trading Cards,SGC,Yes,Pack-pulled,X,SGC <1500 w/Auto,$27.50,25,4/2/2026,"$1,500.00","SGC’s <1500 service offers affordable grading for cards valued up to $1,500, making it a great option for collectors looking for reliable grading without the higher price tag. Whether you’re submitting sports cards or trading card games (TCGs), SGC delivers consistent, high-quality results. Every card submitted through Market 2 Mint is wiped down and carefully handled throughout the grading process."
Trading Cards,SGC,No,X,X,SGC <3500,$60.00,20,3/28/2026,"$3,500.00","SGC’s <3500 service offers affordable grading for cards valued up to $3,500, making it a great option for collectors looking for reliable grading without the higher price tag. Whether you’re submitting sports cards or trading card games (TCGs), SGC delivers consistent, high-quality results. Every card submitted through Market 2 Mint is wiped down and carefully handled throughout the grading process."
Trading Cards,SGC,Yes,Pack-pulled,X,SGC <3500 w/Auto,$65.00,20,3/28/2026,"$3,500.00","SGC’s <3500 service offers affordable grading for cards valued up to $3,500, making it a great option for collectors looking for reliable grading without the higher price tag. Whether you’re submitting sports cards or trading card games (TCGs), SGC delivers consistent, high-quality results. Every card submitted through Market 2 Mint is wiped down and carefully handled throughout the grading process."
Trading Cards,SGC,No,X,X,SGC <7500,$105.00,15,3/23/2026,"$7,500.00","SGC’s <7500 service offers affordable grading for cards valued up to $7,500, making it a great option for collectors looking for reliable grading without the higher price tag. Whether you’re submitting sports cards or trading card games (TCGs), SGC delivers consistent, high-quality results. Every card submitted through Market 2 Mint is wiped down and carefully handled throughout the grading process."
Trading Cards,SGC,Yes,Pack-pulled,X,SGC <7500 w/Auto,$110.00,15,3/23/2026,"$7,500.00","SGC’s <7500 service offers affordable grading for cards valued up to $7,500, making it a great option for collectors looking for reliable grading without the higher price tag. Whether you’re submitting sports cards or trading card games (TCGs), SGC delivers consistent, high-quality results. Every card submitted through Market 2 Mint is wiped down and carefully handled throughout the grading process."
Autograph Quick Opinion,X,X,X,X,BGS Auto Quick Opinion,$15.00,5,3/13/2026,Not applicable,"Unsure about an autograph? We’ll scan it and submit it to BGS for a “Likely to Pass” or “Unlikely to Pass” opinion — helping you avoid costly submission fees. Buying online? Just send us the link."
Memorabilia,JSA,X,X,X,JSA Memorabilia Certification,$25.00,15,3/23/2026,Not applicable,"Certify virtually any type of memorabilia. What you pay today is JSA’s minimum for any autograph authentication. We will let you know final costs based on signatures before proceeding and what you pay today, will be applied regardless of authenticity outcome."
Memorabilia,PSA,X,X,X,PSA/DNA Memorabilia Certification,$25.00,75,5/22/2026,Not applicable,"Certify virtually any type of memorabilia. What you pay today is JSA’s minimum for any autograph authentication. We will let you know final costs based on signatures before proceeding and what you pay today, will be applied regardless of authenticity outcome."
Slab Cracking,X,X,X,X,M2M Slab Cracking Service,$10.00,5,3/13/2026,$500.00,"We will carefully remove your card from its existing holder. Whether you're preparing for a resubmission, or a fresh evaluation, we handle your card with precision and care. Every cracked card is wiped down and prepped for its next destination."
Slab Cracking,X,X,X,X,M2M Slab Cracking Service,$15.00,5,3/13/2026,"$1,500.00","We will carefully remove your card from its existing holder. Whether you're preparing for a resubmission, or a fresh evaluation, we handle your card with precision and care. Every cracked card is wiped down and prepped for its next destination."
Slab Cracking,X,X,X,X,M2M Slab Cracking Service,$20.00,5,3/13/2026,"$3,000.00","We will carefully remove your card from its existing holder. Whether you're preparing for a resubmission, or a fresh evaluation, we handle your card with precision and care. Every cracked card is wiped down and prepped for its next destination."
Crossover,PSA,No,X,Card Grade Only,PSA Crossover Plus,$54.99,30,4/7/2026,$500.00,"Submit cards graded by another company for evaluation and potential crossover to PSA. You must specify your minimum acceptable grade(s) in the checkout notes; if PSA does not meet those minimums, the card will be returned in its current holder and the evaluation fee will still apply."
Crossover,PSA,Yes,Pack-pulled,Card & Autograph Grade,PSA Crossover Plus (Dual),$69.99,50,4/27/2026,$500.00,"Submit cards graded by another company for evaluation and potential crossover to PSA. You must specify your minimum acceptable grade(s) in the checkout notes; if PSA does not meet those minimums, the card will be returned in its current holder and the evaluation fee will still apply."
Crossover,PSA,Yes,Pack-pulled,Autograph Grade Only,PSA Crossover Plus (Auto),$69.99,50,4/27/2026,$500.00,"Submit cards graded by another company for evaluation and potential crossover to PSA. You must specify your minimum acceptable grade(s) in the checkout notes; if PSA does not meet those minimums, the card will be returned in its current holder and the evaluation fee will still apply."
Crossover,PSA,Yes,Pack-pulled,Authenticate Only,PSA Crossover Plus (Auth),$69.99,50,4/27/2026,$500.00,"Submit cards graded by another company for evaluation and potential crossover to PSA. You must specify your minimum acceptable grade(s) in the checkout notes; if PSA does not meet those minimums, the card will be returned in its current holder and the evaluation fee will still apply."
Crossover,PSA,No,X,Card Grade Only,PSA Crossover Express,$154.00,15,3/23/2026,"$2,500.00","Submit cards graded by another company for evaluation and potential crossover to PSA. You must specify your minimum acceptable grade(s) in the checkout notes; if PSA does not meet those minimums, the card will be returned in its current holder and the evaluation fee will still apply."
Crossover,PSA,Yes,Pack-pulled,Card & Autograph Grade,PSA Crossover Express (Dual),$204.00,25,4/2/2026,"$2,500.00","Submit cards graded by another company for evaluation and potential crossover to PSA. You must specify your minimum acceptable grade(s) in the checkout notes; if PSA does not meet those minimums, the card will be returned in its current holder and the evaluation fee will still apply."
Crossover,PSA,Yes,Pack-pulled,Autograph Grade Only,PSA Crossover Express (Auto),$204.00,25,4/2/2026,"$2,500.00","Submit cards graded by another company for evaluation and potential crossover to PSA. You must specify your minimum acceptable grade(s) in the checkout notes; if PSA does not meet those minimums, the card will be returned in its current holder and the evaluation fee will still apply."
Crossover,PSA,Yes,Pack-pulled,Authenticate Only,PSA Crossover Express (Auth),$204.00,25,4/2/2026,"$2,500.00","Submit cards graded by another company for evaluation and potential crossover to PSA. You must specify your minimum acceptable grade(s) in the checkout notes; if PSA does not meet those minimums, the card will be returned in its current holder and the evaluation fee will still apply."
Crossover,BGS,No,X,Card Grade Only,BGS Crossover Standard,$40.00,35,4/12/2026,Not applicable,"Upgrade to Beckett’s iconic grading with BGS’s Crossover service. Submit cards currently graded by other companies (like PSA, CGC, or SGC) for re-evaluation under Beckett’s strict grading standards. Your card will remain sealed in its original slab unless BGS determines it meets or exceeds your grade requirements. Ideal for collectors seeking Beckett’s full subgrades and strong market presence."
Crossover,BGS,Yes,Pack-pulled,Card Grade Only,BGS Crossover Standard,$45.00,35,4/12/2026,Not applicable,"Upgrade to Beckett’s iconic grading with BGS’s Crossover service. Submit cards currently graded by other companies (like PSA, CGC, or SGC) for re-evaluation under Beckett’s strict grading standards. Your card will remain sealed in its original slab unless BGS determines it meets or exceeds your grade requirements. Ideal for collectors seeking Beckett’s full subgrades and strong market presence."
Reholder,PSA,X,X,X,PSA Reholder <$2000,$17.99,80,5/27/2026,"$2,000.00","Reholder service is perfect for replacing damaged, scratched, or outdated cases. Your card will be removed from its current holder and re-encapsulated in a brand-new, tamper-evident slab. This is a great option for improving display quality or ensuring long-term protection. Card may be re-evaluated if damage is present."
Reholder,PSA,X,X,X,PSA Reholder <$5000,$34.99,65,5/12/2026,"$5,000.00","Reholder service is perfect for replacing damaged, scratched, or outdated cases. Your card will be removed from its current holder and re-encapsulated in a brand-new, tamper-evident slab. This is a great option for improving display quality or ensuring long-term protection. Card may be re-evaluated if damage is present."
Reholder,PSA,X,X,X,"PSA Reholder <$20,000",$79.99,17,3/25/2026,"$20,000.00","Reholder service is perfect for replacing damaged, scratched, or outdated cases. Your card will be removed from its current holder and re-encapsulated in a brand-new, tamper-evident slab. This is a great option for improving display quality or ensuring long-term protection. Card may be re-evaluated if damage is present."
Reholder,BGS,X,X,X,BGS Reholder,$17.99,45,4/22/2026,Not applicable,"Reholder service is perfect for replacing damaged, scratched, or outdated cases. Your card will be removed from its current holder and re-encapsulated in a brand-new, tamper-evident slab. This is a great option for improving display quality or ensuring long-term protection. Card may be re-evaluated if damage is present."
Reholder,CGC,X,X,X,CGC Reholder,$15.00,30,4/7/2026,Not applicable,"Reholder service is perfect for replacing damaged, scratched, or outdated cases. Your card will be removed from its current holder and re-encapsulated in a brand-new, tamper-evident slab. This is a great option for improving display quality or ensuring long-term protection. Card may be re-evaluated if damage is present."
Event Tickets,BGS,No,X,Ticket Grade,BGS Ticket,$40.00,45,4/22/2026,$999.00,"Holding on to a ticket stub from that unforgettable concert? What about the last time your team went all the way to the World Series? Whether it's a milestone or a memory, your ticket can be preserved and graded by Beckett's team of experts."
Event Tickets,BGS,No,X,Authenticate Only,BGS Ticket (Auth),$40.00,45,4/22/2026,$999.00,"Holding on to a ticket stub from that unforgettable concert? What about the last time your team went all the way to the World Series? Whether it's a milestone or a memory, your ticket can be preserved and graded by Beckett's team of experts."
Event Tickets,BGS,Yes,Pack-pulled,Ticket Grade & Auto Authentication,BGS Ticket w/Auto,$55.00,45,4/22/2026,$999.00,"Holding on to a ticket stub from that unforgettable concert? What about the last time your team went all the way to the World Series? Whether it's a milestone or a memory, your ticket can be preserved and graded by Beckett's team of experts."
Event Tickets,BGS,Yes,Aftermarket,Ticket Grade & Auto Authentication,BGS Ticket w/Auto,$55.00,45,4/22/2026,$999.00,"Holding on to a ticket stub from that unforgettable concert? What about the last time your team went all the way to the World Series? Whether it's a milestone or a memory, your ticket can be preserved and graded by Beckett's team of experts."
Event Tickets,BGS,Yes,Pack-pulled,Authenticate Only,BGS Ticket w/Auto (Auth),$55.00,45,4/22/2026,$999.00,"Holding on to a ticket stub from that unforgettable concert? What about the last time your team went all the way to the World Series? Whether it's a milestone or a memory, your ticket can be preserved and graded by Beckett's team of experts."
Event Tickets,BGS,Yes,Aftermarket,Authenticate Only,BGS Ticket w/Auto (Auth),$55.00,45,4/22/2026,$999.00,"Holding on to a ticket stub from that unforgettable concert? What about the last time your team went all the way to the World Series? Whether it's a milestone or a memory, your ticket can be preserved and graded by Beckett's team of experts."
Event Tickets,BGS,No,X,Ticket Grade,BGS Ticket Standard,$85.00,30,4/7/2026,"$4,999.00","Holding on to a ticket stub from that unforgettable concert? What about the last time your team went all the way to the World Series? Whether it's a milestone or a memory, your ticket can be preserved and graded by Beckett's team of experts."
Event Tickets,BGS,No,X,Authenticate Only,BGS Ticket Standard (Auth),$85.00,30,4/7/2026,"$4,999.00","Holding on to a ticket stub from that unforgettable concert? What about the last time your team went all the way to the World Series? Whether it's a milestone or a memory, your ticket can be preserved and graded by Beckett's team of experts."
Event Tickets,BGS,Yes,Pack-pulled,Ticket Grade & Auto Authentication,BGS Ticket Standard w/Auto,$110.00,30,4/7/2026,"$4,999.00","Holding on to a ticket stub from that unforgettable concert? What about the last time your team went all the way to the World Series? Whether it's a milestone or a memory, your ticket can be preserved and graded by Beckett's team of experts."
Event Tickets,BGS,Yes,Aftermarket,Ticket Grade & Auto Authentication,BGS Ticket Standard w/Auto,$110.00,30,4/7/2026,"$4,999.00","Holding on to a ticket stub from that unforgettable concert? What about the last time your team went all the way to the World Series? Whether it's a milestone or a memory, your ticket can be preserved and graded by Beckett's team of experts."
Event Tickets,BGS,Yes,Pack-pulled,Authenticate Only,BGS Ticket Standard w/Auto (Auth),$110.00,30,4/7/2026,"$4,999.00","Holding on to a ticket stub from that unforgettable concert? What about the last time your team went all the way to the World Series? Whether it's a milestone or a memory, your ticket can be preserved and graded by Beckett's team of experts."
Event Tickets,BGS,Yes,Aftermarket,Authenticate Only,BGS Ticket Standard w/Auto (Auth),$110.00,30,4/7/2026,"$4,999.00","Holding on to a ticket stub from that unforgettable concert? What about the last time your team went all the way to the World Series? Whether it's a milestone or a memory, your ticket can be preserved and graded by Beckett's team of experts."
Unopened Packs,PSA,No,X,X,PSA Economy Pack,$60.00,85,6/1/2026,"$4,999.00","Whether it’s vintage or modern, PSA will authenticate, grade, and encapsulate your pack to preserve its condition and enhance its value. All packs submitted through Market 2 Mint are carefully inspected, prepped, and securely handled from start to finish."
Unopened Packs,PSA,No,X,X,PSA Express Pack,$160.00,45,4/22/2026,"$4,999.00","Whether it’s vintage or modern, PSA will authenticate, grade, and encapsulate your pack to preserve its condition and enhance its value. All packs submitted through Market 2 Mint are carefully inspected, prepped, and securely handled from start to finish."
Movies & Videos,CGC,X,X,Grade Item,CGC Movies & Videos,$55.00,55,5/2/2026,"$2,500.00","CGC’s Video/Movie Grading service is perfect for sealed VHS tapes, DVDs, and other home video formats valued up to $2,500. This service provides expert authentication, grading, and encapsulation with CGC’s trusted accuracy and presentation. All submissions through Market 2 Mint are carefully inspected, prepped, and securely handled from start to finish."
Movies & Videos,CGC,X,X,Grade + Basic Cleaning,CGC Movies & Videos,$65.00,55,5/2/2026,"$2,500.00","CGC’s Video/Movie Grading service is perfect for sealed VHS tapes, DVDs, and other home video formats valued up to $2,500. This service provides expert authentication, grading, and encapsulation with CGC’s trusted accuracy and presentation. All submissions through Market 2 Mint are carefully inspected, prepped, and securely handled from start to finish."
Movies & Videos,CGC,X,X,Grade + Heavy Cleaning,CGC Movies & Videos,$95.00,55,5/2/2026,"$2,500.00","CGC’s Video/Movie Grading service is perfect for sealed VHS tapes, DVDs, and other home video formats valued up to $2,500. This service provides expert authentication, grading, and encapsulation with CGC’s trusted accuracy and presentation. All submissions through Market 2 Mint are carefully inspected, prepped, and securely handled from start to finish."
Comics & Magazines,PSA,No,X,Grade Item,1975 - Newer,$34.99,40,4/17/2026,$400.00,"PSA will accept standard-sized books and sports programs. Each service level includes Premium Imaging and Grader Notes. All comics and magazines graded by PSA are backed by PSA’s authenticity guarantee. Max Size Comic Books and Magazines Accepted: X: 8.65” / Y: 11.65” / Z: .3”"
Comics & Magazines,PSA,No,X,Authenticate Item Only,1975 - Newer (Auth),$34.99,40,4/17/2026,$400.00,"PSA will accept standard-sized books and sports programs. Each service level includes Premium Imaging and Grader Notes. All comics and magazines graded by PSA are backed by PSA’s authenticity guarantee. Max Size Comic Books and Magazines Accepted: X: 8.65” / Y: 11.65” / Z: .3”"
Comics & Magazines,PSA,Yes,X,Grade Item & Auth Auto,1975 - Newer,$55.99,55,5/2/2026,$400.00,"PSA will accept standard-sized books and sports programs. Each service level includes Premium Imaging and Grader Notes. All comics and magazines graded by PSA are backed by PSA’s authenticity guarantee. Max Size Comic Books and Magazines Accepted: X: 8.65” / Y: 11.65” / Z: .3”"
Comics & Magazines,PSA,No,X,Grade Item,1974 - Older,$49.99,50,4/27/2026,$400.00,"PSA will accept standard-sized books and sports programs. Each service level includes Premium Imaging and Grader Notes. All comics and magazines graded by PSA are backed by PSA’s authenticity guarantee. Max Size Comic Books and Magazines Accepted: X: 8.65” / Y: 11.65” / Z: .3”"
Comics & Magazines,PSA,No,X,Authenticate Item Only,1974 - Older (Auth),$49.99,50,4/27/2026,$400.00,"PSA will accept standard-sized books and sports programs. Each service level includes Premium Imaging and Grader Notes. All comics and magazines graded by PSA are backed by PSA’s authenticity guarantee. Max Size Comic Books and Magazines Accepted: X: 8.65” / Y: 11.65” / Z: .3”"
Comics & Magazines,PSA,No,X,Grade Item + Pressing,1974 - Older,$79.99,80,5/27/2026,$400.00,"PSA will accept standard-sized books and sports programs. Each service level includes Premium Imaging and Grader Notes. All comics and magazines graded by PSA are backed by PSA’s authenticity guarantee. Max Size Comic Books and Magazines Accepted: X: 8.65” / Y: 11.65” / Z: .3”"
Comics & Magazines,PSA,No,X,Grade Item,High Value (All Era's),$104.99,20,3/28/2026,"$1,500.00","PSA will accept standard-sized books and sports programs. Each service level includes Premium Imaging and Grader Notes. All comics and magazines graded by PSA are backed by PSA’s authenticity guarantee. Max Size Comic Books and Magazines Accepted: X: 8.65” / Y: 11.65” / Z: .3”"
Comics & Magazines,PSA,No,X,Grade Item + Pressing,High Value (All Era's),$179.99,30,4/7/2026,"$1,500.00","PSA will accept standard-sized books and sports programs. Each service level includes Premium Imaging and Grader Notes. All comics and magazines graded by PSA are backed by PSA’s authenticity guarantee. Max Size Comic Books and Magazines Accepted: X: 8.65” / Y: 11.65” / Z: .3”"
Comics & Magazines,PSA,Yes,X,Grade + Auto Authentication,High Value (All Era's),$149.99,35,4/12/2026,"$1,500.00","PSA will accept standard-sized books and sports programs. Each service level includes Premium Imaging and Grader Notes. All comics and magazines graded by PSA are backed by PSA’s authenticity guarantee. Max Size Comic Books and Magazines Accepted: X: 8.65” / Y: 11.65” / Z: .3”"
Comics & Magazines,PSA,Yes,X,Grade + Auto Auth + Pressing,High Value (All Era's),$224.99,40,4/17/2026,"$1,500.00","PSA will accept standard-sized books and sports programs. Each service level includes Premium Imaging and Grader Notes. All comics and magazines graded by PSA are backed by PSA’s authenticity guarantee. Max Size Comic Books and Magazines Accepted: X: 8.65” / Y: 11.65” / Z: .3”"
Comics & Magazines,PSA,No,X,Grade Item,Super Express (All Era's),$204.00,15,3/23/2026,"$5,000.00","PSA will accept standard-sized books and sports programs. Each service level includes Premium Imaging and Grader Notes. All comics and magazines graded by PSA are backed by PSA’s authenticity guarantee. Max Size Comic Books and Magazines Accepted: X: 8.65” / Y: 11.65” / Z: .3”"
Comics & Magazines,PSA,No,X,Grade Item,Walk-Through (All Era's),$404.00,10,3/18/2026,"$10,000.00","PSA will accept standard-sized books and sports programs. Each service level includes Premium Imaging and Grader Notes. All comics and magazines graded by PSA are backed by PSA’s authenticity guarantee. Max Size Comic Books and Magazines Accepted: X: 8.65” / Y: 11.65” / Z: .3”"`;

export const POLICY = [
  "Turnaround times begin upon induction at grading facilities and are not guaranteed.",
  "Market 2 Mint is not affiliated with this card shop. We take full responsibility for your items while they are in our possession.",
  "Unclaimed items will be considered abandoned after 120 days and three notification attempts.",
  "Inspect returned items at pickup. Claims must be filed within 7 days of shop return notification.",
  "Grading company upcharges will be invoiced as applicable."
];

export const RECOMMENDATIONS = [
  "Take cell photos of your cards before packaging.",
  "Use the provided boxes/envelopes (No One-Touches).",
  "Hand your order directly to a shop attendant."
];

export const TERMS_OF_USE_SECTIONS = [
  {
    title: "Market 2 Mint – Kiosk Terms of Use",
    content: "These Terms of Use (“Terms”) govern your access to and use of Market 2 Mint’s kiosk ordering system, website, and related services (collectively, the “Services”). By submitting items through the kiosk or using our Services, you acknowledge that you have read, understood, and agree to be bound by these Terms."
  },
  {
    title: "Use of Services",
    content: "You agree to use Market 2 Mint Services only for lawful purposes. You may not:\n\n• Violate any applicable law or regulation\n• Submit items you do not legally own or have authority to submit\n• Interfere with or disrupt our systems or services\n• Attempt unauthorized access to Market 2 Mint systems or networks\n• Upload or transmit malicious code, malware, or viruses\n\nMarket 2 Mint reserves the right to refuse service to anyone for any reason permitted by law."
  },
  {
    title: "Submission Authorization",
    content: "By submitting items, you represent and warrant that:\n\n• You are the lawful owner of the items submitted or have authority to submit them\n• The information provided about the items is accurate to the best of your knowledge\n• Items submitted do not violate any laws or intellectual property rights"
  },
  {
    title: "Role of Market 2 Mint",
    content: "Market 2 Mint acts solely as a submission facilitator and logistics intermediary for third-party grading services such as PSA, BGS, SGC, CGC, and others.\n\nMarket 2 Mint:\n• Does not determine grading results\n• Does not guarantee authentication outcomes\n• Does not control grading company turnaround times\n\nAll grading decisions are made solely by the grading company."
  },
  {
    title: "Turnaround Times",
    content: "Estimated turnaround times are determined by grading companies and begin only once items are inducted into the grading company’s system. Turnaround times are estimates and are not guaranteed.\n\nMarket 2 Mint is not responsible for delays caused by grading companies, shipping carriers, customs inspections, or other external factors."
  },
  {
    title: "Declared Value and Service Level Limits",
    content: "Each grading service offered through Market 2 Mint includes a maximum declared value limit, which is displayed to the customer at the time of service selection. By selecting a service tier, the customer confirms that the declared value of the submitted item does not exceed the maximum value permitted for that service level.\n\nThe declared value selected by the customer determines:\n• eligibility for the grading service tier\n• insurance coverage during shipment (if applicable)\n• the maximum liability limit for Market 2 Mint\n\nCustomers are responsible for selecting the appropriate service tier based on the estimated market value of their item. Market 2 Mint is not responsible for incorrect service selection.\n\nIf a grading company determines that an item exceeds the declared value associated with the selected service tier, the grading company may assess an upcharge or service adjustment. Customers agree to pay any such upcharges prior to release or return of the graded item."
  },
  {
    title: "Clause for Services With No Declared Value Limit (Example: BGS)",
    content: "Some grading services may not impose a maximum declared value limit. In these cases, the value entered by the customer during submission will be treated as the official declared value for insurance and liability purposes.\n\nFor submissions without a predefined service value limit:\n• The customer must provide a reasonable declared value at the time of submission.\n• Market 2 Mint’s maximum liability for any loss or damage claim will not exceed the declared value entered by the customer or the amount of service fees paid, whichever is lower.\n• Market 2 Mint reserves the right to request reasonable proof of value in the event of a claim.\n• Failure to provide an accurate declared value may limit or void any claim for loss or damage."
  },
  {
    title: "Excess Value Limitation",
    content: "If the actual market value of a submitted item exceeds the declared value provided during submission, Market 2 Mint’s liability shall remain strictly limited to the declared value selected by the customer, regardless of the item’s actual market value.\n\nCustomers are responsible for ensuring declared values accurately reflect the value of their items."
  },
  {
    title: "Limitation of Liability",
    content: "To the fullest extent permitted by law, Market 2 Mint shall not be liable for:\n\n• grading outcomes\n• grading company determinations\n• delays in grading services\n• market value fluctuations\n• lost profits or consequential damages\n\nMarket 2 Mint’s total liability for any claim shall not exceed the declared value of the submitted item or the amount of service fees paid, whichever is lower."
  },
  {
    title: "Shipping and Transit Risk",
    content: "Submitted items may be transported between:\n\n• partner shops\n• Market 2 Mint facilities\n• grading company facilities\n• shipping carriers\n\nMarket 2 Mint uses reasonable care in packaging and handling items. However, shipping carriers are independent third parties, and Market 2 Mint is not responsible for carrier delays or carrier negligence.\n\nInsurance coverage, if applicable, is limited to declared value."
  },
  {
    title: "Force Majeure",
    content: "Market 2 Mint shall not be responsible for delays or losses caused by events beyond its reasonable control, including but not limited to:\n\n• natural disasters\n• fire\n• theft\n• labor disputes\n• shipping carrier failures\n• government actions\n• grading company operational disruptions"
  },
  {
    title: "Intellectual Property",
    content: "All trademarks, logos, content, and materials displayed on our Services are the property of Market 2 Mint or their respective owners. No content may be reproduced or distributed without prior written consent."
  },
  {
    title: "Changes to Terms",
    content: "Market 2 Mint reserves the right to update these Terms at any time. Continued use of our Services constitutes acceptance of updated Terms."
  }
];

export const TERMS_OF_USE = TERMS_OF_USE_SECTIONS.map(s => `${s.title}\n\n${s.content}`).join('\n\n');


export const SUBMISSION_POLICY_SECTIONS = [
  {
    title: "Market 2 Mint – Submission Policy",
    content: "This policy governs all items submitted through Market 2 Mint."
  },
  {
    title: "Customer Responsibility",
    content: "Customers are responsible for:\n\n• accurately identifying cards or collectibles submitted\n• declaring accurate item values\n• selecting the appropriate grading service tier\n\nMarket 2 Mint is not responsible for errors in customer-provided submission information."
  },
  {
    title: "Card Condition",
    content: "Market 2 Mint does not guarantee the condition of submitted items and does not provide guarantees regarding grading outcomes.\n\nCards may contain defects including but not limited to:\n\n• scratches\n• print lines\n• surface wear\n• edge damage\n• centering issues\n\nGrading companies evaluate these factors independently."
  },
  {
    title: "Grading Company Determinations",
    content: "Authentication, grading, encapsulation, and rejection decisions are made solely by the grading company.\n\nMarket 2 Mint is not responsible for:\n\n• grading outcomes\n• rejection of items\n• altered or trimmed determinations\n• authentication failures"
  },
  {
    title: "Upcharges",
    content: "Grading companies may assess upcharges if the declared value or service tier does not match the card’s determined value.\n\nCustomers are responsible for paying all grading company upcharges prior to release of graded items."
  },
  {
    title: "Shipping & Logistics",
    content: "Standard flat-rate shipping is $24.00. M2M internal service shipping is waived when bundled with any other grading submission (PSA, BGS, CGC, or SGC). A $5.00 surcharge applies if Local Group services (PSA, BGS) are mixed with Florida Group services (CGC, SGC), or if both Florida Group services are ordered together."
  },
  {
    title: "Handling and Packaging",
    content: "Market 2 Mint handles all items with reasonable care.\n\nHowever, Market 2 Mint is not responsible for damage caused by:\n\n• pre-existing card defects\n• grading company handling\n• grading company encapsulation\n• shipping carrier handling"
  },
  {
    title: "Liability Cap",
    content: "Market 2 Mint’s liability for any loss or damage claim shall not exceed the declared value of the item or the amount of service fees paid, whichever is lower.\n\nProof of value may be required for claims."
  },
  {
    title: "Limited Liability & Inspection Period",
    content: "Market 2 Mint (M2M) and the Host Partner Card Shop are not liable for any discrepancies, damages, or grading errors once the item has been collected by the customer. Customers are required to inspect all graded items at the time of pickup. Any claims regarding item condition or grading errors must be filed within 7 business days of the 'Returned to Shop' notification. M2M maintains video records of all inductions for 30 days; claims made after this window cannot be verified and will not be honored."
  },
  {
    title: "Abandoned Items",
    content: "Items not claimed within 120 days after notification may be considered abandoned.\n\nMarket 2 Mint will attempt to notify the customer at least three times. After abandonment, Market 2 Mint reserves the right to:\n\n• charge storage fees\n• liquidate items to recover costs\n• dispose of items in accordance with applicable law"
  },
  {
    title: "Partner Shop Locations",
    content: "Market 2 Mint may operate submission services through partner shop locations.\n\nPartner shops act only as drop-off and pickup locations and are not responsible for grading outcomes or submission processing."
  }
];

export const PRIVACY_POLICY_SECTIONS = [
  {
    title: "Market 2 Mint – Privacy Policy",
    content: "Market 2 Mint respects your privacy and is committed to protecting your personal information."
  },
  {
    title: "Information We Collect",
    content: "We may collect the following types of information:\n\n• Name\n• Email address\n• Phone number\n• Shipping or billing address\n• Submission details\n• Declared item values\n• Payment transaction information\n• Images uploaded through submission systems\n• Device information such as IP address and browser type"
  },
  {
    title: "How We Use Your Information",
    content: "We use collected information to:\n\n• process grading submissions\n• manage customer orders\n• communicate with customers\n• provide customer support\n• improve our services"
  },
  {
    title: "Third-Party Service Providers",
    content: "Market 2 Mint may share information with trusted third-party providers necessary to operate our services, including:\n\n• payment processors\n• shipping carriers\n• grading companies\n• technology service providers\n\nThese parties may only use information for the purpose of providing services to Market 2 Mint."
  },
  {
    title: "Data Security",
    content: "We implement reasonable administrative, technical, and physical safeguards to protect personal information against unauthorized access, alteration, disclosure, or destruction."
  },
  {
    title: "Data Retention",
    content: "Market 2 Mint may retain submission records, order information, and uploaded images for operational purposes, accounting requirements, and dispute resolution."
  },
  {
    title: "Customer Privacy Rights",
    content: "Depending on your location, you may have rights regarding your personal information, including:\n\n• requesting access to your data\n• requesting correction of inaccurate information\n• requesting deletion of personal information where permitted by law"
  },
  {
    title: "Children's Privacy",
    content: "Market 2 Mint services are not directed toward children under 13 years of age."
  },
  {
    title: "Policy Updates",
    content: "Market 2 Mint may update this Privacy Policy periodically. Updated policies will be posted on our website and may be displayed on kiosk systems."
  }
];

export const PRIVACY_POLICY = PRIVACY_POLICY_SECTIONS.map(s => `${s.title}\n\n${s.content}`).join('\n\n');

