/**
 * THE SERVICE MENU — one record per routable service variant.
 *
 * GENERATED. Do not hand-edit: run `Kiosk v3/build_service_menu.py`, which joins the
 * decision-tree routing in the old `data.ts` CSV to the money in
 * `Kiosk v3/M2M_SERVICES_AND_FEES_CORRECTED_2026-08-05.xlsx` — the sole authority for
 * every price, turnaround and insured value.
 *
 * ⚠️ CUSTOMER PRICES ONLY. `price.employee`, `price.owner` and `cost` are typed here but
 * are ALWAYS null in this file, because everything in this file ships to every kiosk and
 * anything in the bundle is public. Role pricing is resolved server-side after login —
 * see Phase 4 of the brief. The real employee/owner figures live outside this repo, in
 * `Kiosk v3/M2M_SERVICE_MENU_ROLE_PRICING.json`.
 *
 * `active: false` replaces the hardcoded PSA-Value suppression that used to sit inside
 * the CSV parser, marked "temporarily", still live six weeks later. Retiring a service is
 * now a data change that shows up in a diff.
 *
 * ADDING A NEW GRADING COMPANY is a data change: append records with their six question
 * values and re-run the generator. MBA (Base $25.00 / Express $60.00) is priced and final
 * in the sheet but marked HOLD — NOT YET LIVE and is deliberately absent, because its
 * decision-tree routing has not been supplied. Do not invent routing for it.
 */

/** The six decision-tree answers, in order. `null` = not routable yet. */
export type QuestionPath = [string, string, string, string, string, string];

export interface ServicePrice {
  /** The only tier that may ship to a kiosk. */
  customer: number;
  /** Always null in the bundle. Resolved server-side after a role login. */
  employee: number | null;
  /** Always null in the bundle. Resolved server-side after a role login. */
  owner: number | null;
}

export interface ServiceRecord {
  category: string;
  name: string;
  /** null when the sheet carries a service the decision tree cannot yet reach. */
  questions: QuestionPath | null;
  price: ServicePrice;
  /** What M2M pays the grader. Never shipped — always null here. */
  cost: number | null;
  businessDays: number;
  maxInsuredValue: string;
  /** false = retired/suspended. Kept as history; filtered out of the flow. */
  active: boolean;
  status: string;
}

/**
 * Customer-facing copy, keyed by service name.
 *
 * Held separately because copy belongs to a SERVICE while `questions` belongs to a ROUTE,
 * and one service is reachable by up to eight routes. Inlining it per record duplicated
 * every paragraph up to eight times and cost ~50KB in a bundle that a shop's WiFi has to
 * deliver before the kiosk paints.
 */
export const SERVICE_COPY: Record<string, { description: string; details: string }> = {
  "Pregrading": { description: "Cards from Year 2000 and Newer Only. This service is not required if you only wish to receive the standard submission wipe-down— all Market 2 Mint submissions automatically include our professional wipe-down service. Our team will carefully evaluate each card's surface, centering, edges, and corners, then provide you with an interactive report highlighting key defects and projected grades. You can easily mark your submit and non-submit selections directly within the report, and your items will be processed/returned accordingly.", details: "Disclaimer: M2M adheres to rigorous grading standards; however, all pre-evaluations are subjective opinions and not a guarantee of final grades. Actual results may vary. By proceeding with this service, the customer acknowledges that M2M is not liable for discrepancies between our assessment and a third-party's final grade." },
  "PSA Value Bulk": { description: "Value Bulk service is ideal for collectors who want a complete, worry-free grading experience. Designed for modern-era cards with pack-pulled autographs (Only the card can be graded), this service includes a professional wipe-down to help remove surface dust and fingerprints prior to submission. We handle every step with care: providing fresh card savers & penny sleeves, capturing high-resolution scans of your cards, and ensuring secure hand-delivery and pickup directly at PSA. An excellent choice for collectors seeking professional preparation, reliable grading, and long-term protection to help maximize their cards' appearance and value.", details: "No minimum or maximum submission number required to submit on this service. Can have a pack-pulled autograph only, but only the card can be graded. Is a dealer/member only service." },
  "PSA Vintage & Value": { description: "PSA's Value and Vintage services are ideal for those who prefer value over speed. Whether you're grading for resale or personal collection, this service delivers trusted results with efficiency and a wide variety of grading options. All cards submitted through Market 2 Mint receive a full wipe-down and secure handling throughout the process.", details: "No minimum or maximum submission number required to submit on this service. This is the lowest submission tier for Vintage cards." },
  "PSA Value & Vintage Dual": { description: "PSA's Value and Vintage services are ideal for those who prefer value over speed. Whether you're grading for resale or personal collection, this service delivers trusted results with efficiency and a wide variety of grading options. All cards submitted through Market 2 Mint receive a full wipe-down and secure handling throughout the process.", details: "No minimum or maximum submission number required to submit on this service. This is the lowest submission tier for Vintage cards." },
  "PSA Value Plus": { description: "PSA's Value Plus service offers a faster turnaround for mid-value cards—perfect for collectors who want efficiency without the higher cost of premium tiers. As always, Market 2 Mint provides wipe-downs and secure handling for every card submitted.", details: "" },
  "PSA Value Plus Dual": { description: "PSA's Value Plus Dual service offers a faster turnaround for mid-value cards—perfect for collectors who want dual service efficiency without the higher cost of premium tiers. As always, Market 2 Mint provides wipe-downs and secure handling for every card submitted.", details: "" },
  "PSA Value Max": { description: "PSA's Value Max option offers a solid balance between cost and turnaround time. All cards submitted through Market 2 Mint receive a wipe-down and are handled with care from start to finish.", details: "" },
  "PSA Max Dual": { description: "PSA's Value Max Dual option offers a solid balance between cost and turnaround time for pack-pulled and aftermarket autographs. All cards submitted through Market 2 Mint receive a wipe-down and are handled with care from start to finish.", details: "" },
  "PSA Regular": { description: "PSA's Regular service is ideal for grading mid-to-high value cards with a faster turnaround than other options. Whether you're grading for resale or personal collection, this service delivers trusted results with efficiency. All cards submitted through Market 2 Mint receive a full wipe-down and secure handling throughout the process.", details: "" },
  "PSA Regular Dual": { description: "PSA's Regular Dual service is ideal for grading mid-to-high value cards with a faster turnaround than other options. Whether you're grading for resale or personal collection, this service delivers trusted results with efficiency. All cards submitted through Market 2 Mint receive a full wipe-down and secure handling throughout the process.", details: "" },
  "PSA Express": { description: "PSA's Express service offers priority turnaround and grader notes. Perfect for collectors or sellers who need quick results without sacrificing PSA's trusted grading standards. All submissions through Market 2 Mint include card prep, wipe-down, and secure handling from start to finish.", details: "Will have grader notes" },
  "PSA Express Dual": { description: "PSA's Express Dual service offers priority turnaround and grader notes. Perfect for collectors or sellers who need quick results without sacrificing PSA's trusted grading standards. All submissions through Market 2 Mint include card prep, wipe-down, and secure handling from start to finish.", details: "Will have grader notes" },
  "PSA Super Express": { description: "Need fast grading for your high-value cards? PSA's Super Express service is built for speed and security, offering fast turnaround and grader notes. This service ensures your premium items are prioritized and handled with top-tier care. All submissions through Market 2 Mint include a professional wipe-down and secure processing from start to finish.", details: "Will have grader notes" },
  "PSA Super Express Dual": { description: "Need fast grading for your high-value cards? PSA's Super Express Dual service is built for speed and security, offering fast turnaround and grader notes. This service ensures your premium items are prioritized and handled with top-tier care. All submissions through Market 2 Mint include a professional wipe-down and secure processing from start to finish.", details: "Will have grader notes" },
  "BGS Base": { description: "Beckett's Base service offers reliable grading with no maximum declared value, making it ideal for a wide range of cards—from modern to vintage. This service provides full subgrades and the iconic BGS label. All cards submitted through Market 2 Mint receive a full wipe-down and are securely handled from prep to return.", details: "Only pack-pulled autograph cards can be submitted. All autographs are graded by BGS, but only 10's make it to the label." },
  "BGS Base w/Auto": { description: "Beckett's Base service offers reliable grading with no maximum declared value, making it ideal for a wide range of cards—from modern to vintage. This service provides full subgrades and the iconic BGS label. All cards submitted through Market 2 Mint receive a full wipe-down and are securely handled from prep to return.", details: "Only pack-pulled autograph cards can be submitted. All autographs are graded by BGS, but only 10's make it to the label." },
  "BGS Standard": { description: "BGS Standard offers a great balance between turnaround time and cost, with no maximum declared value. Perfect for collectors looking for reliable grading with full subgrades and Beckett's signature labeling. All cards submitted through Market 2 Mint are wiped down and securely handled throughout the submission process.", details: "Only pack-pulled autograph cards can be submitted. All autographs are graded by BGS, but only 10's make it to the label." },
  "BGS Standard w/Auto": { description: "BGS Standard offers a great balance between turnaround time and cost, with no maximum declared value. Perfect for collectors looking for reliable grading with full subgrades and Beckett's signature labeling. All cards submitted through Market 2 Mint are wiped down and securely handled throughout the submission process.", details: "Only pack-pulled autograph cards can be submitted. All autographs are graded by BGS, but only 10's make it to the label." },
  "BGS Express": { description: "Need faster grading without sacrificing accuracy? BGS Express offers a quicker turnaround—with no maximum declared value. This service includes full subgrades and Beckett's premium labeling, ideal for collectors and sellers who want their cards back fast. Every card submitted through Market 2 Mint receives a careful wipe-down and is securely processed from start to finish.", details: "Only pack-pulled autograph cards can be submitted. All autographs are graded by BGS, but only 10's make it to the label." },
  "BGS Express w/Auto": { description: "Need faster grading without sacrificing accuracy? BGS Express offers a quicker turnaround—with no maximum declared value. This service includes full subgrades and Beckett's premium labeling, ideal for collectors and sellers who want their cards back fast. Every card submitted through Market 2 Mint receives a careful wipe-down and is securely processed from start to finish.", details: "Only pack-pulled autograph cards can be submitted. All autographs are graded by BGS, but only 10's make it to the label." },
  "BGS Priority": { description: "Need faster grading without sacrificing accuracy? BGS Priority offers a quicker turnaround—with no maximum declared value. This service includes full subgrades and Beckett's premium labeling, ideal for collectors and sellers who want their cards back fast. Every card submitted through Market 2 Mint receives a careful wipe-down and is securely processed from start to finish.", details: "Only pack-pulled autograph cards can be submitted. All autographs are graded by BGS, but only 10's make it to the label." },
  "BGS Priority w/Auto": { description: "Need faster grading without sacrificing accuracy? BGS Priority offers a quicker turnaround—with no maximum declared value. This service includes full subgrades and Beckett's premium labeling, ideal for collectors and sellers who want their cards back fast. Every card submitted through Market 2 Mint receives a careful wipe-down and is securely processed from start to finish.", details: "Only pack-pulled autograph cards can be submitted. All autographs are graded by BGS, but only 10's make it to the label." },
  "CGC Economy": { description: "CGC's Economy service is an ideal option for collectors looking for reliable grading without the higher price tag. Whether you're submitting sports cards or trading card games (TCGs), CGC delivers consistent, high-quality results. Every card submitted through Market 2 Mint is wiped down and carefully handled throughout the grading process.", details: "Only pack-pulled autograph cards can be submitted, but only the card will be graded." },
  "CGC Economy w/Auto": { description: "CGC's Economy service is an ideal option for collectors looking for reliable grading without the higher price tag. Whether you're submitting sports cards or trading card games (TCGs), CGC delivers consistent, high-quality results. Every card submitted through Market 2 Mint is wiped down and carefully handled throughout the grading process.", details: "Only pack-pulled autograph cards can be submitted, but only the card will be graded." },
  "CGC Standard": { description: "CGC's Standard service is a great choice for grading mid-value cards, offering a perfect blend of turnaround time and affordability. Whether it's sports cards or TCGs, you'll receive accurate, professional grading with CGC's trusted standards. All cards submitted through Market 2 Mint are wiped down and securely handled from submission to return.", details: "Only pack-pulled autograph cards can be submitted, but only the card will be graded." },
  "CGC Standard w/Auto": { description: "CGC's Standard service is a great choice for grading mid-value cards, offering a perfect blend of turnaround time and affordability. Whether it's sports cards or TCGs, you'll receive accurate, professional grading with CGC's trusted standards. All cards submitted through Market 2 Mint are wiped down and securely handled from submission to return.", details: "Only pack-pulled autograph cards can be submitted, but only the card will be graded." },
  "CGC Express": { description: "CGC's Express service is ideal for grading high-value cards quickly and securely. Perfect for serious collectors or sellers who need fast, reliable results. All cards submitted through Market 2 Mint are wiped down and professionally handled from start to finish.", details: "Only pack-pulled autograph cards can be submitted, but only the card will be graded." },
  "CGC Express w/Auto": { description: "CGC's Express service is ideal for grading high-value cards quickly and securely. Perfect for serious collectors or sellers who need fast, reliable results. All cards submitted through Market 2 Mint are wiped down and professionally handled from start to finish.", details: "Only pack-pulled autograph cards can be submitted, but only the card will be graded." },
  "SGC Standard": { description: "SGC's <1500 service offers affordable grading for cards valued up to $1,500, making it a great option for collectors looking for reliable grading without the higher price tag. Whether you're submitting sports cards or trading card games (TCGs), SGC delivers consistent, high-quality results. Every card submitted through Market 2 Mint is wiped down and carefully handled throughout the grading process.", details: "Only pack-pulled autograph cards can be submitted. All autographs are graded by SGC, but only 10's make it to the label." },
  "SGC <1500 w/Auto": { description: "SGC's <1500 service offers affordable grading for cards valued up to $1,500, making it a great option for collectors looking for reliable grading without the higher price tag. Whether you're submitting sports cards or trading card games (TCGs), SGC delivers consistent, high-quality results. Every card submitted through Market 2 Mint is wiped down and carefully handled throughout the grading process.", details: "Only pack-pulled autograph cards can be submitted. All autographs are graded by SGC, but only 10's make it to the label." },
  "SGC Expedited": { description: "SGC's <3500 service offers affordable grading for cards valued up to $7,500, making it a great option for collectors looking for reliable grading without the higher price tag. Whether you're submitting sports cards or trading card games (TCGs), SGC delivers consistent, high-quality results. Every card submitted through Market 2 Mint is wiped down and carefully handled throughout the grading process.", details: "Only pack-pulled autograph cards can be submitted. All autographs are graded by SGC, but only 10's make it to the label." },
  "SGC <3500 w/Auto": { description: "SGC's <3500 service offers affordable grading for cards valued up to $7,500, making it a great option for collectors looking for reliable grading without the higher price tag. Whether you're submitting sports cards or trading card games (TCGs), SGC delivers consistent, high-quality results. Every card submitted through Market 2 Mint is wiped down and carefully handled throughout the grading process.", details: "Only pack-pulled autograph cards can be submitted. All autographs are graded by SGC, but only 10's make it to the label." },
  "BGS Auto Quick Opinion": { description: "Unsure about an autograph? We'll scan it and submit it to BGS for a 'Likely to Pass' or 'Unlikely to Pass' opinion – helping you avoid costly submission fees. Buying online? Just send us the link.", details: "Use this service first if even the slightest doubt about the authenticity of an autograph." },
  "JSA Authentication": { description: "Certify virtually any type of memorabilia. What you pay today is JSA's minimum for any autograph authentication. We will let you know final costs based on signatures before proceeding and what you pay today, will be applied regardless of authenticity outcome.", details: "Final cost is determined by factors such as who signed, how many signed, and even what they signed. Once everything has been properly assessed, we will notify you with the total, and you will be able to accept or decline." },
  "PSA/DNA Memorabilia Certification": { description: "Certify virtually any type of memorabilia. What you pay today is PSA's minimum for any autograph authentication. We will let you know final costs based on signatures before proceeding and what you pay today, will be applied regardless of authenticity outcome.", details: "Final cost is determined by factors such as who signed, how many signed, and even what they signed. Once everything has been properly assessed, we will notify you with the total, and you will be able to accept or decline." },
  "M2M Slab Cracking Service": { description: "We will carefully remove your card from its existing holder. Whether you're preparing for a resubmission, or a fresh evaluation, we handle your card with precision and care. Every cracked card is wiped down and prepped for its next destination.", details: "" },
  "PSA Crossover Plus Card Only": { description: "Submit cards graded by another company for evaluation and potential crossover to PSA. You must specify your minimum acceptable grade(s) in the checkout notes; if PSA does not meet those minimums, the card will be returned in its current holder and the evaluation fee will still apply.", details: "The customer must specify their minimum acceptable grade for both card and autograph as applicable for the crossover." },
  "PSA Crossover Plus Dual": { description: "Submit cards graded by another company for evaluation and potential crossover to PSA. You must specify your minimum acceptable grade(s) in the checkout notes; if PSA does not meet those minimums, the card will be returned in its current holder and the evaluation fee will still apply.", details: "The customer must specify their minimum acceptable grade for both card and autograph as applicable for the crossover." },
  "PSA Crossover Express": { description: "Submit cards graded by another company for evaluation and potential crossover to PSA. You must specify your minimum acceptable grade(s) in the checkout notes; if PSA does not meet those minimums, the card will be returned in its current holder and the evaluation fee will still apply.", details: "The customer must specify their minimum acceptable grade for both card and autograph as applicable for the crossover." },
  "PSA Crossover Express Dual": { description: "Submit cards graded by another company for evaluation and potential crossover to PSA. You must specify your minimum acceptable grade(s) in the checkout notes; if PSA does not meet those minimums, the card will be returned in its current holder and the evaluation fee will still apply.", details: "The customer must specify their minimum acceptable grade for both card and autograph as applicable for the crossover." },
  "BGS Crossover": { description: "Upgrade to Beckett's iconic grading with BGS's Crossover service. Submit cards currently graded by other companies (like PSA, CGC, or SGC) for re-evaluation under Beckett's strict grading standards. Your card will remain sealed in its original slab unless BGS determines it meets or exceeds your grade requirements. Ideal for collectors seeking Beckett's full subgrades and strong market presence.", details: "The customer must specify their minimum acceptable grade for both card and autograph as applicable for the crossover." },
  "BGS Crossover w/Auto": { description: "Upgrade to Beckett's iconic grading with BGS's Crossover service. Submit cards currently graded by other companies (like PSA, CGC, or SGC) for re-evaluation under Beckett's strict grading standards. Your card will remain sealed in its original slab unless BGS determines it meets or exceeds your grade requirements. Ideal for collectors seeking Beckett's full subgrades and strong market presence.", details: "The customer must specify their minimum acceptable grade for both card and autograph as applicable for the crossover." },
  "PSA Reholder <$2,000": { description: "PSA's Reholder service is perfect for replacing damaged, scratched, or outdated cases. Your card will be removed from its current holder and re-encapsulated in a brand-new, tamper-evident PSA slab. This is a great option for improving display quality or ensuring long-term protection. Card may be re-evaluated if damage is present.", details: "Grades will remain the same unless the slab is damaged, and that damage translated through to the card. If this occurred, the card will be regraded to account for the added defects." },
  "BGS Reholder": { description: "Want to update your BGS slab? BGS' Reholder service is perfect for replacing damaged, scratched, or outdated cases. Your card will be removed from its current holder and re-encapsulated in a brand-new, tamper-evident BGS slab. This is a great option for improving display quality or ensuring long-term protection. Card may be re-evaluated if damage is present.", details: "Grades will remain the same unless the slab is damaged, and that damage translated through to the card. If this occurred, the card will be regraded to account for the added defects." },
  "CGC Reholder": { description: "CGC's Reholder service is perfect for replacing damaged, scratched, or outdated cases. Your card will be removed from its current holder and re-encapsulated in a brand-new, tamper-evident CGC slab. This is a great option for improving display quality or ensuring long-term protection. Card may be re-evaluated if damage is present.", details: "Grades will remain the same unless the slab is damaged, and that damage translated through to the card. If this occurred, the card will be regraded to account for the added defects." },
  "PSA Value Ticket": { description: "Holding on to a ticket stub from that unforgettable concert? What about the last time your team went all the way to the World Series? Whether it's a milestone or a memory, your ticket can be preserved and graded by PSA's team of experts.", details: "" },
  "PSA Ticket w/Auto": { description: "Holding on to a ticket stub from that unforgettable concert? What about the last time your team went all the way to the World Series? Whether it's a milestone or a memory, your ticket can be preserved and graded by PSA's team of experts.", details: "" },
  "PSA Regular Ticket": { description: "Holding on to a ticket stub from that unforgettable concert? What about the last time your team went all the way to the World Series? Whether it's a milestone or a memory, your ticket can be preserved and graded by PSA's team of experts.", details: "" },
  "PSA Economy Pack": { description: "Whether it's vintage or modern, PSA will authenticate, grade, and encapsulate your pack to preserve its condition and enhance its value. All packs submitted through Market 2 Mint are carefully inspected, prepped, and securely handled from start to finish.", details: "" },
  "CGC Standard Video": { description: "CGC's Video/Movie Grading service is perfect for sealed VHS tapes, DVDs, and other home video formats valued up to $2,500. This service provides expert authentication, grading, and encapsulation with CGC's trusted accuracy and presentation. All submissions through Market 2 Mint are carefully inspected, prepped, and securely handled from start to finish.", details: "" },
  "CGC Standard Video w/Basic Cleaning": { description: "CGC's Video/Movie Grading service is perfect for sealed VHS tapes, DVDs, and other home video formats valued up to $2,500. This service provides expert authentication, grading, and encapsulation with CGC's trusted accuracy and presentation. All submissions through Market 2 Mint are carefully inspected, prepped, and securely handled from start to finish.", details: "" },
  "CGC Standard Video w/Heavy Cleaning": { description: "CGC's Video/Movie Grading service is perfect for sealed VHS tapes, DVDs, and other home video formats valued up to $2,500. This service provides expert authentication, grading, and encapsulation with CGC's trusted accuracy and presentation. All submissions through Market 2 Mint are carefully inspected, prepped, and securely handled from start to finish.", details: "" },
  "PSA Video Games": { description: "From loose cartridges to Complete-in-Box (CIB), sealed media, and beyond, PSA authenticates and grades your favorite media across various consoles and platforms. In an era where physical media is disappearing, we help you preserve your most important gaming and media memories, recognizing them for the art and history that they are. PSA's experts provide authentication, grading, and encapsulation services for your most treasured items, whether you're just starting to collect or you're expanding your collection.", details: "" },
  "1975 - Newer": { description: "PSA will accept standard-sized books and sports programs. Each service level includes Premium Imaging and Grader Notes. All comics and magazines graded by PSA are backed by PSA's authenticity guarantee. Max Size Comic Books and Magazines Accepted: X: 8.65\\ / Y: 11.65\\ / Z: .3\\,,,,,,,,,,,,,,,,,,,,,,", details: "" },
};

export const SERVICE_MENU: ServiceRecord[] = [
  {
    category: "Pregrading",
    name: "Pregrading",
    questions: ["Pregrading", "Skip Question", "Skip Question", "Skip Question", "Skip Question", "2000 - Newer Only"],
    price: { customer: 7.0, employee: null, owner: null },
    cost: null,
    businessDays: 7,
    maxInsuredValue: "NA",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "PSA Value Bulk",
    questions: ["Trading Cards", "PSA", "No", "Skip Question", "Skip Question", "Card Grade Only"],
    price: { customer: 29.99, employee: null, owner: null },
    cost: null,
    businessDays: 160,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Value Bulk",
    questions: ["Trading Cards", "PSA", "Yes", "Pack-pulled", "1999 - Newer", "Card Grade Only"],
    price: { customer: 29.99, employee: null, owner: null },
    cost: null,
    businessDays: 160,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Vintage & Value",
    questions: ["Trading Cards", "PSA", "No", "Skip Question", "Skip Question", "Card Grade Only"],
    price: { customer: 37.99, employee: null, owner: null },
    cost: null,
    businessDays: 120,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Vintage & Value",
    questions: ["Trading Cards", "PSA", "No", "Skip Question", "Skip Question", "Authenticate Only"],
    price: { customer: 37.99, employee: null, owner: null },
    cost: null,
    businessDays: 120,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Vintage & Value",
    questions: ["Trading Cards", "PSA", "Yes", "Pack-pulled", "1999 - Newer", "Card Grade Only"],
    price: { customer: 37.99, employee: null, owner: null },
    cost: null,
    businessDays: 120,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Vintage & Value",
    questions: ["Trading Cards", "PSA", "Yes", "Pack-pulled", "1999 - Newer", "Authenticate Card Only"],
    price: { customer: 37.99, employee: null, owner: null },
    cost: null,
    businessDays: 120,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Value & Vintage Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Aftermarket", "Either", "Card Grade Only"],
    price: { customer: 47.99, employee: null, owner: null },
    cost: null,
    businessDays: 130,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Value & Vintage Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Aftermarket", "Either", "Auth Card & Auto Only"],
    price: { customer: 47.99, employee: null, owner: null },
    cost: null,
    businessDays: 130,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Value & Vintage Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Either", "Either", "Card & Autograph Grade"],
    price: { customer: 47.99, employee: null, owner: null },
    cost: null,
    businessDays: 130,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Value & Vintage Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Either", "Either", "Autograph Grade Only"],
    price: { customer: 47.99, employee: null, owner: null },
    cost: null,
    businessDays: 130,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Value Plus",
    questions: ["Trading Cards", "PSA", "No", "Skip Question", "Skip Question", "Card Grade Only"],
    price: { customer: 54.99, employee: null, owner: null },
    cost: null,
    businessDays: 80,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Value Plus",
    questions: ["Trading Cards", "PSA", "No", "Skip Question", "Skip Question", "Authenticate Only"],
    price: { customer: 54.99, employee: null, owner: null },
    cost: null,
    businessDays: 80,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Value Plus",
    questions: ["Trading Cards", "PSA", "Yes", "Pack-pulled", "1999 - Newer", "Card Grade Only"],
    price: { customer: 54.99, employee: null, owner: null },
    cost: null,
    businessDays: 80,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Value Plus",
    questions: ["Trading Cards", "PSA", "Yes", "Pack-pulled", "1999 - Newer", "Authenticate Card Only"],
    price: { customer: 54.99, employee: null, owner: null },
    cost: null,
    businessDays: 80,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Value Plus Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Aftermarket", "Either", "Card Grade Only"],
    price: { customer: 69.99, employee: null, owner: null },
    cost: null,
    businessDays: 90,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Value Plus Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Aftermarket", "Either", "Auth Card & Auto Only"],
    price: { customer: 69.99, employee: null, owner: null },
    cost: null,
    businessDays: 90,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Value Plus Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Either", "Either", "Card & Autograph Grade"],
    price: { customer: 69.99, employee: null, owner: null },
    cost: null,
    businessDays: 90,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Value Plus Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Either", "Either", "Autograph Grade Only"],
    price: { customer: 69.99, employee: null, owner: null },
    cost: null,
    businessDays: 90,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Value Max",
    questions: ["Trading Cards", "PSA", "No", "Skip Question", "Skip Question", "Card Grade Only"],
    price: { customer: 69.99, employee: null, owner: null },
    cost: null,
    businessDays: 50,
    maxInsuredValue: "$1,000.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Value Max",
    questions: ["Trading Cards", "PSA", "No", "Skip Question", "Skip Question", "Authenticate Only"],
    price: { customer: 69.99, employee: null, owner: null },
    cost: null,
    businessDays: 50,
    maxInsuredValue: "$1,000.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Value Max",
    questions: ["Trading Cards", "PSA", "Yes", "Pack-pulled", "1999 - Newer", "Card Grade Only"],
    price: { customer: 69.99, employee: null, owner: null },
    cost: null,
    businessDays: 50,
    maxInsuredValue: "$1,000.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Value Max",
    questions: ["Trading Cards", "PSA", "Yes", "Pack-pulled", "1999 - Newer", "Authenticate Card Only"],
    price: { customer: 69.99, employee: null, owner: null },
    cost: null,
    businessDays: 50,
    maxInsuredValue: "$1,000.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Max Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Aftermarket", "Either", "Card Grade Only"],
    price: { customer: 89.99, employee: null, owner: null },
    cost: null,
    businessDays: 60,
    maxInsuredValue: "$1,000.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Max Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Aftermarket", "Either", "Auth Card & Auto Only"],
    price: { customer: 89.99, employee: null, owner: null },
    cost: null,
    businessDays: 60,
    maxInsuredValue: "$1,000.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Max Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Either", "Either", "Card & Autograph Grade"],
    price: { customer: 89.99, employee: null, owner: null },
    cost: null,
    businessDays: 60,
    maxInsuredValue: "$1,000.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Max Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Either", "Either", "Autograph Grade Only"],
    price: { customer: 89.99, employee: null, owner: null },
    cost: null,
    businessDays: 60,
    maxInsuredValue: "$1,000.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "PSA Regular",
    questions: ["Trading Cards", "PSA", "No", "Skip Question", "Skip Question", "Card Grade Only"],
    price: { customer: 84.99, employee: null, owner: null },
    cost: null,
    businessDays: 40,
    maxInsuredValue: "$1,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "PSA Regular",
    questions: ["Trading Cards", "PSA", "No", "Skip Question", "Skip Question", "Authenticate Only"],
    price: { customer: 84.99, employee: null, owner: null },
    cost: null,
    businessDays: 40,
    maxInsuredValue: "$1,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "PSA Regular",
    questions: ["Trading Cards", "PSA", "Yes", "Pack-pulled", "1999 - Newer", "Card Grade Only"],
    price: { customer: 84.99, employee: null, owner: null },
    cost: null,
    businessDays: 40,
    maxInsuredValue: "$1,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "PSA Regular",
    questions: ["Trading Cards", "PSA", "Yes", "Pack-pulled", "1999 - Newer", "Authenticate Card Only"],
    price: { customer: 84.99, employee: null, owner: null },
    cost: null,
    businessDays: 40,
    maxInsuredValue: "$1,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "PSA Regular Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Aftermarket", "Either", "Card Grade Only"],
    price: { customer: 109.99, employee: null, owner: null },
    cost: null,
    businessDays: 50,
    maxInsuredValue: "$1,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "PSA Regular Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Aftermarket", "Either", "Auth Card & Auto Only"],
    price: { customer: 109.99, employee: null, owner: null },
    cost: null,
    businessDays: 50,
    maxInsuredValue: "$1,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "PSA Regular Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Either", "Either", "Card & Autograph Grade"],
    price: { customer: 109.99, employee: null, owner: null },
    cost: null,
    businessDays: 50,
    maxInsuredValue: "$1,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "PSA Regular Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Either", "Either", "Autograph Grade Only"],
    price: { customer: 109.99, employee: null, owner: null },
    cost: null,
    businessDays: 50,
    maxInsuredValue: "$1,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "PSA Express",
    questions: ["Trading Cards", "PSA", "No", "Skip Question", "Skip Question", "Card Grade Only"],
    price: { customer: 154.0, employee: null, owner: null },
    cost: null,
    businessDays: 30,
    maxInsuredValue: "$2,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "PSA Express",
    questions: ["Trading Cards", "PSA", "No", "Skip Question", "Skip Question", "Authenticate Only"],
    price: { customer: 154.0, employee: null, owner: null },
    cost: null,
    businessDays: 30,
    maxInsuredValue: "$2,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "PSA Express",
    questions: ["Trading Cards", "PSA", "Yes", "Pack-pulled", "1999 - Newer", "Card Grade Only"],
    price: { customer: 154.0, employee: null, owner: null },
    cost: null,
    businessDays: 30,
    maxInsuredValue: "$2,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "PSA Express",
    questions: ["Trading Cards", "PSA", "Yes", "Pack-pulled", "1999 - Newer", "Authenticate Card Only"],
    price: { customer: 154.0, employee: null, owner: null },
    cost: null,
    businessDays: 30,
    maxInsuredValue: "$2,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "PSA Express Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Aftermarket", "Either", "Card Grade Only"],
    price: { customer: 204.0, employee: null, owner: null },
    cost: null,
    businessDays: 40,
    maxInsuredValue: "$2,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "PSA Express Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Aftermarket", "Either", "Auth Card & Auto Only"],
    price: { customer: 204.0, employee: null, owner: null },
    cost: null,
    businessDays: 40,
    maxInsuredValue: "$2,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "PSA Express Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Either", "Either", "Card & Autograph Grade"],
    price: { customer: 204.0, employee: null, owner: null },
    cost: null,
    businessDays: 40,
    maxInsuredValue: "$2,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "PSA Express Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Either", "Either", "Autograph Grade Only"],
    price: { customer: 204.0, employee: null, owner: null },
    cost: null,
    businessDays: 40,
    maxInsuredValue: "$2,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "PSA Super Express",
    questions: ["Trading Cards", "PSA", "No", "Skip Question", "Skip Question", "Card Grade Only"],
    price: { customer: 354.0, employee: null, owner: null },
    cost: null,
    businessDays: 20,
    maxInsuredValue: "$5,000.00",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Trading Cards",
    name: "PSA Super Express",
    questions: ["Trading Cards", "PSA", "No", "Skip Question", "Skip Question", "Authenticate Only"],
    price: { customer: 354.0, employee: null, owner: null },
    cost: null,
    businessDays: 20,
    maxInsuredValue: "$5,000.00",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Trading Cards",
    name: "PSA Super Express",
    questions: ["Trading Cards", "PSA", "Yes", "Pack-pulled", "1999 - Newer", "Card Grade Only"],
    price: { customer: 354.0, employee: null, owner: null },
    cost: null,
    businessDays: 20,
    maxInsuredValue: "$5,000.00",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Trading Cards",
    name: "PSA Super Express",
    questions: ["Trading Cards", "PSA", "Yes", "Pack-pulled", "1999 - Newer", "Authenticate Card Only"],
    price: { customer: 354.0, employee: null, owner: null },
    cost: null,
    businessDays: 20,
    maxInsuredValue: "$5,000.00",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Trading Cards",
    name: "PSA Super Express Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Aftermarket", "Either", "Card Grade Only"],
    price: { customer: 475.0, employee: null, owner: null },
    cost: null,
    businessDays: 20,
    maxInsuredValue: "$5,000.00",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Trading Cards",
    name: "PSA Super Express Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Aftermarket", "Either", "Auth Card & Auto Only"],
    price: { customer: 475.0, employee: null, owner: null },
    cost: null,
    businessDays: 20,
    maxInsuredValue: "$5,000.00",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Trading Cards",
    name: "PSA Super Express Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Either", "Either", "Card & Autograph Grade"],
    price: { customer: 475.0, employee: null, owner: null },
    cost: null,
    businessDays: 20,
    maxInsuredValue: "$5,000.00",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Trading Cards",
    name: "PSA Super Express Dual",
    questions: ["Trading Cards", "PSA", "Yes", "Either", "Either", "Autograph Grade Only"],
    price: { customer: 475.0, employee: null, owner: null },
    cost: null,
    businessDays: 20,
    maxInsuredValue: "$5,000.00",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Trading Cards",
    name: "BGS Base",
    questions: ["Trading Cards", "BGS", "No", "Skip Question", "Skip Question", "Card Grade Only"],
    price: { customer: 25.0, employee: null, owner: null },
    cost: null,
    businessDays: 95,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "BGS Base w/Auto",
    questions: ["Trading Cards", "BGS", "Yes", "Pack-pulled", "1999 - Newer Only", "Card & Auto Grade"],
    price: { customer: 30.0, employee: null, owner: null },
    cost: null,
    businessDays: 100,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "BGS Standard",
    questions: ["Trading Cards", "BGS", "No", "Skip Question", "Skip Question", "Card Grade Only"],
    price: { customer: 40.0, employee: null, owner: null },
    cost: null,
    businessDays: 45,
    maxInsuredValue: "$2,000.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "BGS Standard w/Auto",
    questions: ["Trading Cards", "BGS", "Yes", "Pack-pulled", "1999 - Newer Only", "Card & Auto Grade"],
    price: { customer: 45.0, employee: null, owner: null },
    cost: null,
    businessDays: 50,
    maxInsuredValue: "$2,000.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Trading Cards",
    name: "BGS Express",
    questions: ["Trading Cards", "BGS", "No", "Skip Question", "Skip Question", "Card Grade Only"],
    price: { customer: 85.0, employee: null, owner: null },
    cost: null,
    businessDays: 15,
    maxInsuredValue: "$3,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "BGS Express w/Auto",
    questions: ["Trading Cards", "BGS", "Yes", "Pack-pulled", "1999 - Newer Only", "Card & Auto Grade"],
    price: { customer: 90.0, employee: null, owner: null },
    cost: null,
    businessDays: 20,
    maxInsuredValue: "$3,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "BGS Priority",
    questions: ["Trading Cards", "BGS", "No", "Skip Question", "Skip Question", "Card Grade Only"],
    price: { customer: 150.0, employee: null, owner: null },
    cost: null,
    businessDays: 25,
    maxInsuredValue: "NA",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Trading Cards",
    name: "BGS Priority w/Auto",
    questions: ["Trading Cards", "BGS", "Yes", "Pack-pulled", "1999 - Newer Only", "Card & Auto Grade"],
    price: { customer: 155.0, employee: null, owner: null },
    cost: null,
    businessDays: 30,
    maxInsuredValue: "NA",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Trading Cards",
    name: "CGC Economy",
    questions: ["Trading Cards", "CGC", "No", "Skip Question", "Skip Question", "Card Grade Only"],
    price: { customer: 25.0, employee: null, owner: null },
    cost: null,
    businessDays: 45,
    maxInsuredValue: "$1,000.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "CGC Economy w/Auto",
    questions: ["Trading Cards", "CGC", "Yes", "Pack-pulled", "1999 - Newer Only", "Card Grade Only"],
    price: { customer: 27.5, employee: null, owner: null },
    cost: null,
    businessDays: 45,
    maxInsuredValue: "$1,000.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Trading Cards",
    name: "CGC Standard",
    questions: ["Trading Cards", "CGC", "No", "Skip Question", "Skip Question", "Card Grade Only"],
    price: { customer: 60.0, employee: null, owner: null },
    cost: null,
    businessDays: 25,
    maxInsuredValue: "$3,000.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "CGC Standard w/Auto",
    questions: ["Trading Cards", "CGC", "Yes", "Pack-pulled", "1999 - Newer Only", "Card Grade Only"],
    price: { customer: 65.0, employee: null, owner: null },
    cost: null,
    businessDays: 25,
    maxInsuredValue: "$3,000.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Trading Cards",
    name: "CGC Express",
    questions: ["Trading Cards", "CGC", "No", "Skip Question", "Skip Question", "Card Grade Only"],
    price: { customer: 105.0, employee: null, owner: null },
    cost: null,
    businessDays: 15,
    maxInsuredValue: "$10,000.00",
    active: true,
    status: "Available",
  },
  {
    category: "Trading Cards",
    name: "CGC Express w/Auto",
    questions: ["Trading Cards", "CGC", "Yes", "Pack-pulled", "1999 - Newer Only", "Card Grade Only"],
    price: { customer: 110.0, employee: null, owner: null },
    cost: null,
    businessDays: 15,
    maxInsuredValue: "$10,000.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Trading Cards",
    name: "SGC Standard",
    questions: ["Trading Cards", "SGC", "No", "Skip Question", "Skip Question", "Card Grade Only"],
    price: { customer: 25.0, employee: null, owner: null },
    cost: null,
    businessDays: 75,
    maxInsuredValue: "$1,500.00",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Trading Cards",
    name: "SGC <1500 w/Auto",
    questions: ["Trading Cards", "SGC", "Yes", "Pack-pulled", "1999 - Newer Only", "Card Grade Only"],
    price: { customer: 30.0, employee: null, owner: null },
    cost: null,
    businessDays: 60,
    maxInsuredValue: "$1,500.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Trading Cards",
    name: "SGC Expedited",
    questions: ["Trading Cards", "SGC", "No", "Skip Question", "Skip Question", "Card Grade Only"],
    price: { customer: 175.0, employee: null, owner: null },
    cost: null,
    businessDays: 15,
    maxInsuredValue: "$3,500.00",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Trading Cards",
    name: "SGC <3500 w/Auto",
    questions: ["Trading Cards", "SGC", "Yes", "Pack-pulled", "1999 - Newer Only", "Card Grade Only"],
    price: { customer: 180.0, employee: null, owner: null },
    cost: null,
    businessDays: 15,
    maxInsuredValue: "$3,500.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Autograph Quick Opinion",
    name: "BGS Auto Quick Opinion",
    questions: ["Autograph Quick Opinion", "Skip Question", "Skip Question", "Skip Question", "Skip Question", "Skip Question"],
    price: { customer: 20.0, employee: null, owner: null },
    cost: null,
    businessDays: 5,
    maxInsuredValue: "NA",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Memorabilia",
    name: "JSA Authentication",
    questions: ["Memorabilia", "JSA", "Skip Question", "Skip Question", "Skip Question", "Skip Question"],
    price: { customer: 25.0, employee: null, owner: null },
    cost: null,
    businessDays: 10,
    maxInsuredValue: "NA",
    active: true,
    status: "Available",
  },
  {
    category: "Memorabilia",
    name: "PSA/DNA Memorabilia Certification",
    questions: ["Memorabilia", "PSA", "Skip Question", "Skip Question", "Skip Question", "Skip Question"],
    price: { customer: 25.0, employee: null, owner: null },
    cost: null,
    businessDays: 95,
    maxInsuredValue: "$2,500",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Slab Cracking",
    name: "M2M Slab Cracking Service",
    questions: ["Slab Cracking", "Skip Question", "Skip Question", "Skip Question", "Skip Question", "Skip Question"],
    price: { customer: 10.0, employee: null, owner: null },
    cost: null,
    businessDays: 5,
    maxInsuredValue: "$500.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Slab Cracking",
    name: "M2M Slab Cracking Service",
    questions: ["Slab Cracking", "Skip Question", "Skip Question", "Skip Question", "Skip Question", "Skip Question"],
    price: { customer: 15.0, employee: null, owner: null },
    cost: null,
    businessDays: 5,
    maxInsuredValue: "$1,500.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Slab Cracking",
    name: "M2M Slab Cracking Service",
    questions: ["Slab Cracking", "Skip Question", "Skip Question", "Skip Question", "Skip Question", "Skip Question"],
    price: { customer: 20.0, employee: null, owner: null },
    cost: null,
    businessDays: 5,
    maxInsuredValue: "$3,000.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Crossover",
    name: "PSA Crossover Plus Card Only",
    questions: ["Crossover", "PSA", "No", "Skip Question", "Skip Question", "Card Grade Only"],
    price: { customer: 54.99, employee: null, owner: null },
    cost: null,
    businessDays: 30,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Crossover",
    name: "PSA Crossover Plus Card Only",
    questions: ["Crossover", "PSA", "No", "Skip Question", "Skip Question", "Authenticate Only"],
    price: { customer: 54.99, employee: null, owner: null },
    cost: null,
    businessDays: 30,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Crossover",
    name: "PSA Crossover Plus Dual",
    questions: ["Crossover", "PSA", "Either", "Either", "Either", "Card Grade Only"],
    price: { customer: 69.99, employee: null, owner: null },
    cost: null,
    businessDays: 50,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Crossover",
    name: "PSA Crossover Plus Dual",
    questions: ["Crossover", "PSA", "Either", "Either", "Either", "Card & Autograph Grade"],
    price: { customer: 69.99, employee: null, owner: null },
    cost: null,
    businessDays: 50,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Crossover",
    name: "PSA Crossover Plus Dual",
    questions: ["Crossover", "PSA", "Either", "Either", "Either", "Autograph Grade Only"],
    price: { customer: 69.99, employee: null, owner: null },
    cost: null,
    businessDays: 50,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Crossover",
    name: "PSA Crossover Plus Dual",
    questions: ["Crossover", "PSA", "Either", "Either", "Either", "Authenticate Card & Auto"],
    price: { customer: 69.99, employee: null, owner: null },
    cost: null,
    businessDays: 50,
    maxInsuredValue: "$500.00",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Crossover",
    name: "PSA Crossover Express",
    questions: ["Crossover", "PSA", "No", "Skip Question", "Skip Question", "Card Grade Only"],
    price: { customer: 154.0, employee: null, owner: null },
    cost: null,
    businessDays: 15,
    maxInsuredValue: "$2,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Crossover",
    name: "PSA Crossover Express",
    questions: ["Crossover", "PSA", "No", "Skip Question", "Skip Question", "Authenticate Only"],
    price: { customer: 154.0, employee: null, owner: null },
    cost: null,
    businessDays: 15,
    maxInsuredValue: "$2,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Crossover",
    name: "PSA Crossover Express Dual",
    questions: ["Crossover", "PSA", "Either", "Either", "Either", "Card Grade Only"],
    price: { customer: 204.0, employee: null, owner: null },
    cost: null,
    businessDays: 25,
    maxInsuredValue: "$2,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Crossover",
    name: "PSA Crossover Express Dual",
    questions: ["Crossover", "PSA", "Either", "Either", "Either", "Card & Autograph Grade"],
    price: { customer: 204.0, employee: null, owner: null },
    cost: null,
    businessDays: 25,
    maxInsuredValue: "$2,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Crossover",
    name: "PSA Crossover Express Dual",
    questions: ["Crossover", "PSA", "Either", "Either", "Either", "Autograph Grade Only"],
    price: { customer: 204.0, employee: null, owner: null },
    cost: null,
    businessDays: 25,
    maxInsuredValue: "$2,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Crossover",
    name: "PSA Crossover Express Dual",
    questions: ["Crossover", "PSA", "Either", "Either", "Either", "Authenticate Card & Auto"],
    price: { customer: 204.0, employee: null, owner: null },
    cost: null,
    businessDays: 25,
    maxInsuredValue: "$2,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Crossover",
    name: "BGS Crossover",
    questions: ["Crossover", "BGS", "No", "Skip Question", "Skip Question", "Card Grade Only"],
    price: { customer: 40.0, employee: null, owner: null },
    cost: null,
    businessDays: 45,
    maxInsuredValue: "NA",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Crossover",
    name: "BGS Crossover w/Auto",
    questions: ["Crossover", "BGS", "Yes", "Pack-pulled", "1999 - Newer", "Card Grade Only"],
    price: { customer: 45.0, employee: null, owner: null },
    cost: null,
    businessDays: 50,
    maxInsuredValue: "NA",
    active: false,
    status: "TEMPORARILY UNAVAILABLE",
  },
  {
    category: "Reholder",
    name: "PSA Reholder <$2,000",
    questions: ["Reholder", "PSA", "Skip Question", "Skip Question", "Skip Question", "Skip Question"],
    price: { customer: 17.99, employee: null, owner: null },
    cost: null,
    businessDays: 90,
    maxInsuredValue: "$2,000.00",
    active: true,
    status: "Available",
  },
  {
    category: "Reholder",
    name: "PSA Reholder <$5,000",
    questions: ["Reholder", "PSA", "Skip Question", "Skip Question", "Skip Question", "Skip Question"],
    price: { customer: 34.99, employee: null, owner: null },
    cost: null,
    businessDays: 65,
    maxInsuredValue: "$5,000.00",
    active: true,
    status: "Available",
  },
  {
    category: "Reholder",
    name: "PSA Reholder <$20,000",
    questions: ["Reholder", "PSA", "Skip Question", "Skip Question", "Skip Question", "Skip Question"],
    price: { customer: 79.99, employee: null, owner: null },
    cost: null,
    businessDays: 17,
    maxInsuredValue: "$20,000.00",
    active: true,
    status: "Available",
  },
  {
    category: "Reholder",
    name: "BGS Reholder",
    questions: ["Reholder", "BGS", "Skip Question", "Skip Question", "Skip Question", "Skip Question"],
    price: { customer: 17.99, employee: null, owner: null },
    cost: null,
    businessDays: 45,
    maxInsuredValue: "NA",
    active: true,
    status: "Available",
  },
  {
    category: "Reholder",
    name: "CGC Reholder",
    questions: ["Reholder", "CGC", "Skip Question", "Skip Question", "Skip Question", "Skip Question"],
    price: { customer: 15.0, employee: null, owner: null },
    cost: null,
    businessDays: 30,
    maxInsuredValue: "NA",
    active: true,
    status: "Available",
  },
  {
    category: "Event Tickets",
    name: "PSA Value Ticket",
    questions: ["Event Tickets", "PSA", "No", "Skip Question", "Skip Question", "Ticket Grade"],
    price: { customer: 49.99, employee: null, owner: null },
    cost: null,
    businessDays: 45,
    maxInsuredValue: "$500.00",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Event Tickets",
    name: "PSA Value Ticket",
    questions: ["Event Tickets", "PSA", "No", "Skip Question", "Skip Question", "Authenticate Only"],
    price: { customer: 49.99, employee: null, owner: null },
    cost: null,
    businessDays: 45,
    maxInsuredValue: "$500.00",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Event Tickets",
    name: "PSA Ticket w/Auto",
    questions: ["Event Tickets", "PSA", "Yes", "Either", "Either", "Ticket Grade & Auto Authentication"],
    price: { customer: 65.0, employee: null, owner: null },
    cost: null,
    businessDays: 55,
    maxInsuredValue: "$500.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Event Tickets",
    name: "PSA Ticket w/Auto",
    questions: ["Event Tickets", "PSA", "Yes", "Either", "Either", "Authenticate Only"],
    price: { customer: 65.0, employee: null, owner: null },
    cost: null,
    businessDays: 55,
    maxInsuredValue: "$500.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Event Tickets",
    name: "PSA Regular Ticket",
    questions: ["Event Tickets", "PSA", "No", "Skip Question", "Skip Question", "Ticket Grade"],
    price: { customer: 84.99, employee: null, owner: null },
    cost: null,
    businessDays: 25,
    maxInsuredValue: "$1,500.00",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Event Tickets",
    name: "PSA Regular Ticket",
    questions: ["Event Tickets", "PSA", "No", "Skip Question", "Skip Question", "Authenticate Only"],
    price: { customer: 84.99, employee: null, owner: null },
    cost: null,
    businessDays: 25,
    maxInsuredValue: "$1,500.00",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Event Tickets",
    name: "PSA Ticket w/Auto",
    questions: ["Event Tickets", "PSA", "Yes", "Either", "Either", "Ticket Grade & Auto Authentication"],
    price: { customer: 105.0, employee: null, owner: null },
    cost: null,
    businessDays: 35,
    maxInsuredValue: "$1,500.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Event Tickets",
    name: "PSA Ticket w/Auto",
    questions: ["Event Tickets", "PSA", "Yes", "Either", "Either", "Authenticate Only"],
    price: { customer: 105.0, employee: null, owner: null },
    cost: null,
    businessDays: 35,
    maxInsuredValue: "$1,500.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Unopened Packs",
    name: "PSA Economy Pack",
    questions: ["Unopened Packs", "PSA", "No", "Skip Question", "Skip Question", "Skip Question"],
    price: { customer: 65.0, employee: null, owner: null },
    cost: null,
    businessDays: 95,
    maxInsuredValue: "$1,000.00",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Unopened Packs",
    name: "PSA Express Pack",
    questions: ["Unopened Packs", "PSA", "No", "Skip Question", "Skip Question", "Skip Question"],
    price: { customer: 165.0, employee: null, owner: null },
    cost: null,
    businessDays: 55,
    maxInsuredValue: "$2,500.00",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Movies & Games",
    name: "CGC Standard Video",
    questions: ["Movies & Games", "CGC", "Skip Question", "Skip Question", "Skip Question", "Grade Item"],
    price: { customer: 65.0, employee: null, owner: null },
    cost: null,
    businessDays: 55,
    maxInsuredValue: "$2,500.00",
    active: true,
    status: "Available",
  },
  {
    category: "Movies & Games",
    name: "CGC Standard Video w/Basic Cleaning",
    questions: ["Movies & Games", "CGC", "Skip Question", "Skip Question", "Skip Question", "Grade + Basic Cleaning"],
    price: { customer: 75.0, employee: null, owner: null },
    cost: null,
    businessDays: 60,
    maxInsuredValue: "$2,500.00",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Movies & Games",
    name: "CGC Standard Video w/Heavy Cleaning",
    questions: ["Movies & Games", "CGC", "Skip Question", "Skip Question", "Skip Question", "Grade + Heavy Cleaning"],
    price: { customer: 115.0, employee: null, owner: null },
    cost: null,
    businessDays: 65,
    maxInsuredValue: "$2,500.00",
    active: true,
    status: "NEW / CHANGED",
  },
  {
    category: "Movies & Games",
    name: "PSA Video Games",
    questions: ["Movies & Games", "PSA", "Skip Question", "Skip Question", "Skip Question", "Grade Game"],
    price: { customer: 65.0, employee: null, owner: null },
    cost: null,
    businessDays: 30,
    maxInsuredValue: "Unlimited",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Movies & Games",
    name: "PSA Video Games",
    questions: ["Movies & Games", "PSA", "Skip Question", "Skip Question", "Skip Question", "Grade Game"],
    price: { customer: 95.0, employee: null, owner: null },
    cost: null,
    businessDays: 15,
    maxInsuredValue: "Unlimited",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Movies & Games",
    name: "PSA Video Games",
    questions: ["Movies & Games", "PSA", "Skip Question", "Skip Question", "Skip Question", "Grade Game"],
    price: { customer: 95.0, employee: null, owner: null },
    cost: null,
    businessDays: 15,
    maxInsuredValue: "Unlimited",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Comics & Magazines",
    name: "1975 - Newer",
    questions: ["Comics & Magazines", "PSA", "No", "Skip Question", "Skip Question", "Grade Item"],
    price: { customer: 34.99, employee: null, owner: null },
    cost: null,
    businessDays: 50,
    maxInsuredValue: "$400.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Comics & Magazines",
    name: "1975 - Newer",
    questions: ["Comics & Magazines", "PSA", "No", "Skip Question", "Skip Question", "Authenticate Item Only"],
    price: { customer: 34.99, employee: null, owner: null },
    cost: null,
    businessDays: 50,
    maxInsuredValue: "$400.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Comics & Magazines",
    name: "1975 - Newer",
    questions: ["Comics & Magazines", "PSA", "Yes", "Skip Question", "Skip Question", "Grade Item & Auth Auto"],
    price: { customer: 55.99, employee: null, owner: null },
    cost: null,
    businessDays: 75,
    maxInsuredValue: "$400.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Comics & Magazines",
    name: "1974 - Older",
    questions: ["Comics & Magazines", "PSA", "No", "Skip Question", "Skip Question", "Grade Item"],
    price: { customer: 49.99, employee: null, owner: null },
    cost: null,
    businessDays: 50,
    maxInsuredValue: "$400.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Comics & Magazines",
    name: "1974 - Older",
    questions: ["Comics & Magazines", "PSA", "No", "Skip Question", "Skip Question", "Authenticate Item Only"],
    price: { customer: 49.99, employee: null, owner: null },
    cost: null,
    businessDays: 50,
    maxInsuredValue: "$400.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Comics & Magazines",
    name: "1974 - Older",
    questions: ["Comics & Magazines", "PSA", "No", "Skip Question", "Skip Question", "Grade Item + Pressing"],
    price: { customer: 79.99, employee: null, owner: null },
    cost: null,
    businessDays: 80,
    maxInsuredValue: "$400.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Comics & Magazines",
    name: "High Value (All Era's)",
    questions: ["Comics & Magazines", "PSA", "No", "Skip Question", "Skip Question", "Grade Item"],
    price: { customer: 104.99, employee: null, owner: null },
    cost: null,
    businessDays: 20,
    maxInsuredValue: "$1,500.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Comics & Magazines",
    name: "High Value (All Era's)",
    questions: ["Comics & Magazines", "PSA", "No", "Skip Question", "Skip Question", "Grade + Pressing"],
    price: { customer: 179.99, employee: null, owner: null },
    cost: null,
    businessDays: 30,
    maxInsuredValue: "$1,500.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Comics & Magazines",
    name: "High Value (All Era's)",
    questions: ["Comics & Magazines", "PSA", "Yes", "Skip Question", "Skip Question", "Grade + Auto Authentication"],
    price: { customer: 149.99, employee: null, owner: null },
    cost: null,
    businessDays: 35,
    maxInsuredValue: "$1,500.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Comics & Magazines",
    name: "High Value (All Era's)",
    questions: ["Comics & Magazines", "PSA", "Yes", "Skip Question", "Skip Question", "Grade + Auto Auth + Pressing"],
    price: { customer: 224.99, employee: null, owner: null },
    cost: null,
    businessDays: 40,
    maxInsuredValue: "$1,500.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Comics & Magazines",
    name: "Super Express (All Era's)",
    questions: ["Comics & Magazines", "PSA", "No", "Skip Question", "Skip Question", "Grade Item"],
    price: { customer: 204.0, employee: null, owner: null },
    cost: null,
    businessDays: 15,
    maxInsuredValue: "$5,000.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Comics & Magazines",
    name: "Walk-Through (All Era's)",
    questions: ["Comics & Magazines", "PSA", "No", "Skip Question", "Skip Question", "Grade Item"],
    price: { customer: 404.0, employee: null, owner: null },
    cost: null,
    businessDays: 10,
    maxInsuredValue: "$10,000.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Comics & Magazines",
    name: "1975 - Newer",
    questions: ["Comics & Magazines", "CGC Comics", "No", "Skip Question", "Skip Question", "Grade Item"],
    price: { customer: 34.99, employee: null, owner: null },
    cost: null,
    businessDays: 45,
    maxInsuredValue: "$400.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Comics & Magazines",
    name: "1975 - Newer",
    questions: ["Comics & Magazines", "CGC Comics", "No", "Skip Question", "Skip Question", "Grade + Fast Track"],
    price: { customer: 50.99, employee: null, owner: null },
    cost: null,
    businessDays: 25,
    maxInsuredValue: "$400.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Comics & Magazines",
    name: "1974 - Older",
    questions: ["Comics & Magazines", "CGC Comics", "No", "Skip Question", "Skip Question", "Grade Item"],
    price: { customer: 50.99, employee: null, owner: null },
    cost: null,
    businessDays: 45,
    maxInsuredValue: "$400.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Comics & Magazines",
    name: "1974 - Older",
    questions: ["Comics & Magazines", "CGC Comics", "No", "Skip Question", "Skip Question", "Grade + Fast Track + Pressing"],
    price: { customer: 70.99, employee: null, owner: null },
    cost: null,
    businessDays: 60,
    maxInsuredValue: "$400.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Comics & Magazines",
    name: "High Value All Era's",
    questions: ["Comics & Magazines", "CGC Comics", "No", "Skip Question", "Skip Question", "Grade Item"],
    price: { customer: 110.0, employee: null, owner: null },
    cost: null,
    businessDays: 10,
    maxInsuredValue: "$1,000.00",
    active: true,
    status: "UNRECONCILED",
  },
  {
    category: "Comics & Magazines",
    name: "High Value All Era's",
    questions: ["Comics & Magazines", "CGC Comics", "No", "Skip Question", "Skip Question", "Grade Item + Pressing"],
    price: { customer: 200.0, employee: null, owner: null },
    cost: null,
    businessDays: 27,
    maxInsuredValue: "$1,000.00",
    active: true,
    status: "UNRECONCILED",
  },
];

/** Services a customer can actually reach: active, and routable by the question tree. */
export const ACTIVE_SERVICES: ServiceRecord[] = SERVICE_MENU.filter(
  (s) => s.active && s.questions !== null,
);

/** Customer-facing copy for a service, or empty strings if it carries none. */
export const copyFor = (name: string): { description: string; details: string } =>
  SERVICE_COPY[name] ?? { description: '', details: '' };
